import type { BlogPost, BlogSection } from "../blog";

const section = (heading: string, paragraphs: string[], bullets?: string[]): BlogSection => ({ heading, paragraphs, ...(bullets ? { bullets } : {}) });
type Story = Pick<BlogPost, "slug" | "title" | "description" | "category" | "keywords" | "intro" | "sections" | "visual">;
const stories: Story[] = [
  {
    slug: "instagram-dm-campaigns-that-match-customer-intent",
    title: "Choose an Instagram DM Campaign That Matches What People Want",
    description: "Match your Instagram DM campaign to the customer's question: a resource, product detail, booking or conversation. Includes messages and a testing checklist.",
    category: "DM Marketing", visual: "workflow", keywords: ["Instagram DM campaigns", "Instagram automation", "comment to DM"],
    intro: "A useful automated conversation starts with a request. Someone wants a recipe, a product link, a price or a place to book. The mistake is treating all four people as the same lead. Before you build a flow, decide what the person came for and how little they need to do to get it.",
    sections: [
      section("Start with the question in your comments", ["Look at the questions on your recent posts and group them by the next action they need. 'Where can I buy this?' belongs with product delivery. 'Can you send the checklist?' belongs with resource delivery. 'Would this work for me?' needs context and may deserve a person, not a longer automated script.", "Pick one group for your first campaign. A narrow promise makes your caption clearer, your first DM shorter and your results easier to understand. You can add another campaign when the first one works from request through destination."]),
      section("For a resource request, deliver the resource", ["A useful caption names both the resource and the action: 'Comment LIGHT and I will send the lighting checklist.' The first DM can say: 'Here is the lighting checklist from the Reel. Open it below.' The button should name the resource instead of saying 'Click here'.", "Keep the resource available on a mobile-friendly page or send a supported attachment. If collecting an email is part of the exchange, explain that in the original offer. An unexpected form after a promise of an instant download makes the conversation feel like a trap."], ["Trigger: the word used in the caption.", "First message: identify and deliver the promised item.", "Measure: successful delivery and resource use, not just comment volume."]),
      section("For product interest, link to the exact item", ["A product DM should identify the item in the post and point to its current product page. Do not force the customer to search a homepage, and do not hard-code availability into a message that might run for months.", "A good example is: 'This is the linen shirt from the Reel. The product page has the current sizes, price and delivery details.' Questions about fit or a specific order can then go to the appropriate human support process. An automation cannot make a stale destination accurate."]),
      section("For booking intent, make the next step concrete", ["A booking campaign should deliver a service page or appointment link, with a short explanation of what happens next. 'Choose a consultation time here' is more useful than 'We would love to help you transform your business'.", "Keep the distinction between an inquiry and a confirmed booking visible. A comment, a DM and a click are signs of interest. The booking system is where availability and confirmation are handled. Do not report every person who received a link as a booked client."]),
      section("Add questions only when the answer changes the journey", ["Every question costs attention. Ask about the service someone needs if you offer several services. Ask for an email when you have explained why you need it. Do not collect a phone number merely because a field exists.", "In AP3K, begin with the appropriate comment, Story or incoming-DM trigger. Write the first response before adding optional steps. Use a flow when a choice truly needs a different response; a simple link delivery does not need an elaborate branching canvas."]),
      section("Test the complete promise", ["Test from a separate Instagram account using a fresh eligible interaction. Check the public reply if enabled, the private message, every button, the destination and any contact details you intentionally collect. Test an unrelated comment too: it should not receive an offer meant for a specific keyword.", "After launch, review a few real conversations. If people repeatedly ask what to do next, rewrite the message before adding another automation. The goal is a useful next step, not the largest possible flow."], ["Does the caption describe the same resource as the DM?", "Can the destination be used comfortably on a phone?", "Does each question affect the next response?", "Can a person take over when the automation reaches its limit?"]),
    ],
  },
  {
    slug: "sell-products-through-instagram-conversations",
    title: "How to Sell Products Through Better Instagram DM Conversations",
    description: "Build a clearer path from product comments to checkout with relevant Instagram DMs, useful replies and a practical way to measure purchase intent.",
    category: "Ecommerce", visual: "dm-link", keywords: ["sell products on Instagram", "Instagram DM marketing", "ecommerce automation"],
    intro: "Your Reel can explain a product beautifully and still leave shoppers asking where to find it. A relevant DM closes that information gap. The strongest starting point is not a complicated sales script: it is a clear answer, the correct product page and an easy way to ask a question.",
    sections: [
      section("Make one product the focus of the offer", ["Choose a post where the product and its purpose are obvious. If the video shows several items, give viewers a way to identify the one they want. A generic 'Comment SHOP' on a ten-product montage creates work for everyone if the DM only links to your storefront.", "For a single-item post, use a specific caption such as 'Comment LINEN for the shirt details.' Keep the keyword distinct from your other active campaigns. The caption, automation and landing page should all name the same product."]),
      section("Write the DM a helpful store assistant would send", ["Try: 'Here is the linen shirt from the video. Open the product page for current sizes, colors and delivery details.' Follow it with one button labeled 'View the linen shirt'. You have answered the question without pretending to know the customer's size or making an availability promise you cannot maintain.", "Avoid stacking a discount, an email request, a follow request and three links into the first message. If someone asked for a product, provide a direct route to it. A long sequence before the link makes an interested shopper do unnecessary work."]),
      section("Keep price and availability in a maintained destination", ["A DM may keep running after your price changes or a variant sells out. Linking to the current product page reduces the number of places your team must update. If the offer itself expires, assign a person to pause or revise the associated campaign.", "Check the destination on a phone: the right product should appear immediately, variant selection should be obvious and checkout should work. No message sequence can rescue a broken product page. AP3K delivers supported messages; your store remains responsible for catalog details, payment and fulfillment."]),
      section("Use questions to help, not to delay the shopper", ["A person asking 'Is this suitable for a small room?' needs useful context. Offer relevant dimensions or route the question to someone who can advise. Do not respond to every question with the same checkout link.", "You can prepare clear replies for recurring topics such as materials, sizing guidance and your published delivery policy. Escalate order-specific problems through your real support process. Never invent an order status or a delivery date to make an automated answer sound complete."], ["Product question: provide the relevant product information.", "Buying question: offer the correct product or checkout destination.", "Order problem: send the shopper to your actual support process."]),
      section("Measure the gap between attention and purchase", ["Track comments, successful sends, destination visits and orders as separate events. Use campaign-tagged links where your store analytics supports them. A sent DM is not a sale; a click is not a sale either.", "Compare campaigns with similar offers before deciding that one keyword or message 'converts better'. A popular product, a lower price or a stronger Reel can change the result. Write down the campaign dates and what changed so you can interpret the data instead of choosing the biggest number."]),
      section("Launch a small, maintainable campaign", ["Start with one current product and one post. Configure the trigger and message in AP3K, test from another account, then inspect the destination and the first real conversations. Keep one person responsible for updating the offer.", "When the basic path works, consider a relevant follow-up only where the platform's messaging rules and your campaign settings permit it. The follow-up should answer a likely question or add useful context. Repeating 'Buy now' does not make a conversation more helpful."]),
    ],
  },
  {
    slug: "instagram-dm-workflow-for-photographers",
    title: "An Instagram DM Workflow That Gives Photographers More Time to Shoot",
    description: "Turn Instagram photography inquiries into a clear next step with a portfolio, pricing guide and booking process that does not bury clients in questions.",
    category: "Creator Business", visual: "dm-link", keywords: ["Instagram for photographers", "photography inquiries", "Instagram DM automation"],
    intro: "A photography inquiry often arrives while you are editing, traveling or working with a client. You do not need an automated sales pitch to respond usefully. You need a short path that helps the person find the right portfolio, understand your service and reach your real inquiry process.",
    sections: [
      section("Separate inspiration from booking interest", ["Not every comment on a beautiful image is a request for your rates. Keep appreciation comments separate from an explicit invitation such as 'Comment WEDDING for the collection guide.' This lets you respond to actual interest without sending a sales message to everyone who leaves a heart.", "Choose a post that represents the service you are promoting. A portrait client should not land in a wedding inquiry flow simply because that was the last campaign you built."]),
      section("Send a small guide with a clear job", ["Your guide should answer the questions a prospective client needs before an inquiry: what you photograph, where you work, what a session generally includes and where to ask about their date. Keep current pricing in a destination you maintain.", "The DM can be simple: 'Here is the portrait session guide you asked for. It includes the session options and inquiry form.' The guide is the useful content; the message is the signpost. Do not paste your entire service brochure into the first chat bubble."]),
      section("Keep the inquiry form focused", ["Ask for details that help you assess the request, such as service, approximate date and location. Explain where you will reply. Avoid making someone complete an exhaustive creative brief before they know whether you offer the service they need.", "If a question needs a personal answer, keep it personal. An automated introduction can save time while a photographer still reviews fit, travel requirements and creative expectations. Speed should not come at the expense of an accurate quote."]),
      section("Do not promise a date before checking it", ["Sending a booking link is different from confirming a booking. Your actual calendar and contract process determine availability. Make the message clear: 'Submit your preferred date and I will confirm availability' is appropriate when a person reviews requests.", "If you use a live scheduling service for consultations, link to it and test it on mobile. Do not imply that AP3K synchronizes your photography calendar or reserves a session merely because it delivered a DM."]),
      section("Build and test the conversation in AP3K", ["Choose the post or incoming-message trigger that matches your invitation. Write one short response and link to the correct guide. Add contact collection only when it supports the follow-up you have explained to the client.", "Use another Instagram account to test a fresh matching comment. Open the guide from the message, submit a test inquiry through your own process and verify where it arrives. Check that unrelated comments do not trigger the same offer."]),
      section("Review the questions the guide did not answer", ["After a week of real use, review the questions you still answer repeatedly. If everyone asks whether travel is included, improve that part of the guide. If people submit the wrong type of inquiry, change the caption or destination.", "Judge the workflow by useful inquiries and the time it saves your team. A larger contact list is not valuable if the people on it wanted a different service. The best automation quietly handles the repetitive introduction so you can spend more attention on the work and the client."]),
    ],
  },
  {
    slug: "instagram-dm-workflow-for-fitness-coaches",
    title: "Instagram DM Ideas for Fitness Coaches Without the Pushy Sales Script",
    description: "Share useful resources, explain coaching options and handle Instagram inquiries with clear DM messages that respect the person behind the request.",
    category: "Creator Business", visual: "workflow", keywords: ["Instagram fitness marketing", "fitness coach DMs", "Instagram DM automation"],
    intro: "Someone who comments on a training video may want the exercise list, not a consultation. Someone who asks about coaching needs to understand your service, not receive another generic motivational message. A good DM workflow respects the difference and makes the next step obvious.",
    sections: [
      section("Choose a resource you can deliver as promised", ["Start with an educational resource that fits the post: an exercise log, a session-planning worksheet or a description of your coaching process. Describe it accurately in the caption and ask for a memorable keyword.", "Keep general educational material separate from individualized advice. A short Instagram interaction is not enough to assess someone's health, injury history or suitability for a particular program. If the person needs professional assessment, route them to the appropriate process rather than improvising a recommendation in an automated reply."]),
      section("Write the first message around their request", ["For a training log, try: 'Here is the session log from the Reel. You can use it to record your own workouts.' For coaching information: 'Here is how my coaching service works, including what is included and how to inquire.' Each message has one clear destination.", "Avoid claims about guaranteed physical results, artificial urgency or language that pressures someone about their body. You can be confident about what the resource contains without promising what an individual will achieve."]),
      section("Explain contact collection before asking", ["If an email address is necessary for your promised follow-up, say what you will use it for. A person who requested a worksheet should not unexpectedly discover that the only next step is a sales call.", "Use the minimum information needed at this stage. Sensitive personal details belong in your appropriate professional intake process, not an open-ended automated Instagram chat. Keep the first exchange focused on the resource or service the person asked about."]),
      section("Offer a consultation as an option", ["Once the person has the information, an optional consultation link can help someone who wants a conversation. Describe what the consultation covers and whether it has a cost before they book.", "If the person only wants the free resource, let that be a complete interaction. More messages do not automatically produce more trust. A useful, low-pressure experience can matter more than forcing every recipient through the same qualification sequence."]),
      section("Keep the setup small enough to test", ["In AP3K, connect the relevant keyword and post to the response that delivers your resource. Check the message, the link and the mobile destination before publishing. Use a separate account and a fresh eligible interaction for the test.", "If you add a flow with several choices, test every branch. Each button should lead where its label suggests, and each required question should have a useful retry path. Review the first real conversations rather than assuming a successful save means the full experience is clear."]),
      section("Measure interest without inflating the result", ["Separate resource requests, successfully delivered messages, coaching inquiries and confirmed clients. These represent different levels of intent. Compare the effort required to manage the campaign with the useful conversations it creates.", "If the post attracts resource requests but few coaching inquiries, that is information about the offer, not proof that the automation failed. Improve the relationship between your content and your service. Keep the useful resource useful even when the recipient never becomes a client."]),
    ],
  },
];
export const OCTOBER_EDITORIAL: BlogPost[] = stories.map(story => {
  const sections = [...story.sections, { heading: "Build your next conversation", paragraphs: ["Start with the request your audience already makes, then choose a response that gives them a useful next step."], links: [{ label: "Explore AP3K plans", href: "/pricing" }, { label: "Create your first automation", href: "/help/create-automation" }] }];
  const wordCount = [story.intro, ...sections.flatMap(s => [s.heading, ...s.paragraphs, ...(s.bullets || [])])].join(" ").split(/\s+/).length;
  return { ...story, sections, contentLocale: "en", publishedAt: "2026-10-01", updatedAt: "2026-10-01", wordCount, readingTime: `${Math.ceil(wordCount / 220)} min read`, visualAlt: `Original AP3K editorial illustration for ${story.title}`, visualCaption: "Original editorial illustration. Campaign examples explain an approach rather than promising a particular business result." };
});
