import type { BlogPost, BlogSection } from "../blog-catalog";

const links = [{ label: "Current plans and usage", href: "/pricing" }, { label: "AP3K setup tutorial", href: "/tutorials/instagram-comment-to-dm" }];
function guide(title: string, description: string, cover: BlogPost["cover"], intro: string, sections: BlogSection[]): Partial<BlogPost> {
  return { title, seoTitle: `${title} | AP3K`, description, subtitle: description, cover, intro, sections,
    importedArchive: false, contentLocale: "en", updatedAt: "2026-10-09", wordCount: undefined,
    category: "AP3K Product Guides", keywords: ["AP3K", "Instagram automation", title],
  };
}

/** Original product-specific replacements. Publication dates are inherited unchanged. */
export const OCTOBER_INDEXING_REVISIONS: Record<string, Partial<BlogPost>> = {
  "get-started-with-ap3k": guide("Get Started With AP3K: Your First Tested Automation", "Connect Instagram, create a focused comment-to-DM campaign and test the complete delivery path before promoting it.", "instagram-ready",
    "Your first AP3K campaign should answer one request reliably. Start with a single Instagram post, one keyword and one useful destination. This walkthrough separates account setup, message design and delivery testing so a successful preview is not mistaken for a working campaign.", [
      { heading: "Prepare the account and the offer", paragraphs: ["Use an Instagram Business or Creator account you own or are authorized to manage. Decide what someone will receive before writing a caption: a guide, product page, appointment link or another specific resource. Open that destination on a phone and check that it works without your own signed-in session.", "Create an AP3K account, authorize Instagram through the connection controls and confirm the selected username. Check Comments ready and DMs ready separately. If the workspace has several accounts, selecting the correct account is part of the setup, not a detail to postpone until publishing."], screenshot: "instagram-ready" },
      { heading: "Create one predictable entry point", paragraphs: ["Open Automations, create a Post automation and select your test post or Reel. Use a keyword when the caption makes an explicit promise, such as ‘Comment GUIDE for the checklist.’ Enter that keyword in the trigger. Any Comment is appropriate only when the response is relevant to every eligible comment.", "A Story interaction or an incoming inbox message uses a different automation type. If the message never appears, first confirm that your test action matches the configured source. Editing the DM text cannot repair a trigger listening for the wrong event."], screenshot: "trigger" },
      { heading: "Write the response and review the cost", paragraphs: ["Enable a public reply, a DM or both. A simple final DM can deliver the requested resource directly. Add a link button with an accurate label of up to 20 characters. Test the URL, not just the appearance of the phone preview.", "An opener, follow request, contact collection or follow-up introduces another step. Start without steps you do not need. Some features require a paid plan. One successful public reply and one successful DM consume two automated actions, so message count and recipient count are different."], links },
      { heading: "Publish only after reviewing the full path", paragraphs: ["A saved draft does not send messages. Review the trigger, message, link and optional steps, read the policy-check findings, then publish deliberately. A clean safety scan is advisory; it does not guarantee Instagram delivery.", "Use a second Instagram account for the test. Leave a fresh matching comment and confirm each enabled response. Try an unrelated comment to verify the negative path. If an opener is enabled, tap it; if a follow gate is enabled, complete the verification. Inspect activity for failures or intentional skips before promoting the post."], video: true },
      { heading: "What to do after the first successful test", paragraphs: ["Record the selected account, post, keyword, destination and test outcome. Keep the initial campaign easy to explain. Expand to another offer only after the complete interaction works; otherwise several campaigns can repeat the same unnoticed setup error.", "Check usage and delivery activity during the first campaign. A captured contact is not a confirmed purchase. Measure a booking or sale at the destination, and ask support for help with an unexplained error rather than repeatedly sending the same test interaction."], links: [{ label: "Troubleshoot a campaign that does not reply", href: "/docs/troubleshoot/fix-comment-automation-not-working" }] },
    ]),
  "10-ways-ap3k-helps-you-automate-and-scale-instagram-marketing": guide("10 Practical Ways to Use AP3K Instagram Automation", "Ten supported AP3K workflows, with clear plan limits, practical examples and checks before you publish.", "automations",
    "AP3K is useful when an Instagram interaction has a clear next step. These ten examples describe supported workflows, not guaranteed growth results. Choose one that fits your audience and test it before combining several steps.", [
      { heading: "1–3: Deliver the requested information", paragraphs: ["1. Comment-to-DM: offer a specific resource in a post and use its keyword to deliver the link. A GUIDE comment can lead to a checklist; unrelated comments should not match a keyword-only campaign.", "2. Public acknowledgement: enable a short public reply when it helps the person know what happens next. Treat public reply and private delivery as separate actions; the public reply is not proof that a DM arrived.", "3. Incoming DM answers: use Chat automation for an eligible inbox keyword or any-message rule. This is useful when the person messages you directly instead of commenting on a post."], screenshot: "trigger" },
      { heading: "4–6: Add useful conversation steps", paragraphs: ["4. Opening DM: ask the recipient to tap a continuation button before the next message when your flow needs an interaction. The opener is different from an external resource link and does not guarantee primary-inbox placement.", "5. Follow request: on an eligible paid plan, add Ask to follow before final delivery if it is appropriate to the offer. Tell people what to expect and test both following and not-following paths.", "6. Collect information: Pro and Business can ask for an email address or phone number and save it to Contacts. Explain why you need the information. Collection should serve the requested resource or service rather than adding friction by default."], screenshot: "collect-email" },
      { heading: "7–8: Respond with context", paragraphs: ["7. Story automation: configure the supported story mention, reply or reaction that should begin the conversation. Test the chosen event; a working comment campaign does not verify Story delivery.", "8. AI replies: on Pro or Business, add accurate product facts, prices and policies to Knowledge, set Behavior and test in Playground. AI is a good fit for varied questions with known answers. A fixed message is often simpler for delivering one link. Paid AI allowances still apply."], screenshot: "ai-knowledge" },
      { heading: "9–10: Recover and measure carefully", paragraphs: ["9. Backtrack comments: deliberately process eligible comments from the previous seven days using a supported selected-media automation. Publishing does not replay the entire history. Review the post and saved rule first; normal sending limits and duplicate protections remain.", "10. Review activity and contacts: check what matched, what was sent and what was skipped or failed. Export filtered Contacts on a paid plan when you need a CSV. Use destination analytics to verify bookings or purchases; do not label all sends or leads as revenue."], screenshot: "contacts" },
      { heading: "Capacity and promises to avoid", paragraphs: ["Free includes five active automations, 500 automated actions per month and one Instagram account. Pro and Business add capacity and paid features. Unlimited active automations on a paid plan does not mean unlimited messages, AI or freedom from Instagram delivery rules.", "AP3K is not an Instagram publishing scheduler or a tool for messaging arbitrary lists. It cannot guarantee follower growth, sales, uninterrupted service or delivery of every message. Choose a small real test, review the results and expand the workflow that actually helps your customers."], links, video: true },
    ]),
  "how-ap3k-connects-through-instagram-api": guide("How AP3K Connects to Instagram", "Understand professional-account authorization, connection readiness, reconnection and the limits of official Instagram API access.", "instagram-ready",
    "AP3K connects authorized Instagram professional accounts through the supported Instagram API flow. That connection lets the product respond to eligible interactions using the permissions granted by the account owner. It is not a promise that every message will be delivered or a claim of Meta Business Partner status.", [
      { heading: "What you need before connecting", paragraphs: ["Use an Instagram Business or Creator account you own or are authorized to manage. A personal account must be converted before it can use the supported professional-account connection. Confirm which Instagram username you intend to connect, especially if your browser has several Meta sessions.", "Start authorization from AP3K’s account controls and review the requested permissions in the official authorization flow. Do not send your Instagram password, one-time code or access token to support or paste it into an AI chat."], links: [{ label: "Connect Instagram step by step", href: "/docs/getting-started/connect-instagram-account" }] },
      { heading: "Connected is not the only readiness check", paragraphs: ["After returning to AP3K, verify the selected username and the Comments ready and DMs ready indicators. Public comment actions and private messaging have different requirements. A connected profile picture alone does not prove that both paths can deliver.", "Create a small draft tied to the correct account. Review the source, post, trigger and response, then publish when ready and test from another Instagram account. The editor preview shows the intended conversation; delivery activity records what happened when a real eligible event arrived."], screenshot: "instagram-ready" },
      { heading: "Why an authorized connection can still need attention", paragraphs: ["Permissions can change, tokens can require refresh and a competing messaging app can affect conversation control. Account restrictions, messaging eligibility, rate limits and technical outages can also prevent or delay a response. Diagnose the recorded error rather than assuming every failure means the entire connection is broken.", "Use Reconnect Instagram to repair authorization for the same account when appropriate. Use Add Instagram account for a different profile. Before reconnecting or switching tools, note the intended account and test one controlled journey afterward."], links: [{ label: "Another app controls the conversation", href: "/docs/troubleshoot/fix-another-app-controlling-instagram-conversations" }] },
      { heading: "Data and customer responsibilities", paragraphs: ["AP3K stores the account identifiers, automation settings, contact and delivery records needed to provide the service. Stripe handles payment-card details. The Privacy Policy explains service providers, retention, account deletion and optional analytics choices.", "You remain responsible for the offers, messages and recipients in your automations. Official API access does not authorize spam, impersonation, scraping or arbitrary bulk messaging. A policy scan is an advisory review, not approval from Meta."], links: [{ label: "Read AP3K privacy information", href: "/privacy" }, { label: "Read the service terms", href: "/terms" }] },
      { heading: "A useful support report", paragraphs: ["If a connection problem persists, tell support which Instagram username and automation are affected, when you tested, whether the public reply or DM failed and what non-sensitive error appeared. Avoid including credentials or another customer’s private conversation.", "If you manage several profiles, keep a separate test record for each one. A successful response on one connected account does not verify the permissions or campaign settings on another. Check the selected account again before making a change, exporting contacts or asking support to investigate. Keep the original automation intact while investigating. Changing the account, trigger, message and timing together makes it harder to identify the cause. Verify one change with one fresh eligible interaction before trying another."], links: [{ label: "Contact AP3K support", href: "/contact" }] },
    ]),
  "how-to-schedule-automations-with-ap3k": guide("AP3K Timing Controls: Delays, Follow-ups and Drafts", "Separate automation timing from Instagram post scheduling. Learn how to prepare drafts, configure delays and test eligible follow-ups.", "delay-controls",
    "Scheduling a post, delaying a reply and preparing an automation are different tasks. AP3K’s automation editor can configure supported message timing and follow-ups; it should not be described as a tool that publishes Instagram posts for you. This guide explains how to plan a campaign without promising unsupported scheduling behavior.", [
      { heading: "Prepare a draft before promoting the campaign", paragraphs: ["Decide on the offer, keyword and real destination first. Create the appropriate Comment, Story, DM or Flow automation and review its entry point. Saving a draft preserves your work without making it a live campaign.", "When using a specific post, confirm that the selected media is the content your audience will interact with. Do not assume a prepared draft automatically attaches to a future upload. Review the actual post-selection options in your editor and verify the chosen scope before publishing."], links: [{ label: "Choose the post or Reel", href: "/docs/post-automation/choose-which-post-or-reel-to-automate" }] },
      { heading: "Apply a delay to the intended step", paragraphs: ["A delay controls when an eligible action proceeds after its trigger or preceding step. It is not a guarantee of an exact delivery time: the queue, account readiness, usage and Instagram rules still matter. Check each relevant timing control instead of assuming the public-reply delay also controls the final DM.", "Use a short supported delay during a controlled test. Record the trigger time, the expected step and the observed result. If a later message never appears, inspect whether an opener, collection request or follow gate is waiting for input before blaming the timer."], screenshot: "delay-controls" },
      { heading: "Follow-ups need eligibility, not just a timer", paragraphs: ["A comment alone does not authorize an unrestricted sequence of messages. A follow-up requires an eligible inbound DM interaction and an open permitted messaging window. In a post flow, the opener can provide a continuation interaction; the person must actually complete it.", "Conditions such as seen, clicked or followed depend on the signals available to AP3K. A newer reply, paused automation or closed messaging window can stop a scheduled follow-up. Begin with a simple supported condition, verify delivery, then test the condition your campaign needs."], links: [{ label: "Configure conditional follow-ups", href: "/docs/post-automation/send-follow-up-messages-with-conditions" }] },
      { heading: "Separate old comments from future delivery", paragraphs: ["Publishing does not replay the post’s comment history. Backtrack comments is a separate deliberate operation for eligible comments from the previous seven days. It uses the saved rule, normal action allowance and delivery protections.", "Before a launch, test the live journey from another Instagram account. After the launch, use activity records to distinguish queued, waiting, skipped and failed actions. Do not repeatedly restart backtracking or duplicate a campaign to force delivery; that can make the customer journey confusing."], links: [{ label: "Backtracking requirements", href: "/docs/how-tos/backtrack-comments-in-automation" }] },
      { heading: "Campaign timing checklist", paragraphs: ["Keep a short launch record: selected account and media, trigger text, live state, each intentional delay, follow-up condition and the final destination. Ask a second person to run the recipient path when possible. The key question is whether each step delivers useful information at the right point, not whether every available timer is enabled."], bullets: ["Confirm the selected post exists and the automation is Live before promoting its keyword.", "Test the exact delay or condition used by the campaign.", "Check the complete recipient interaction, not only the first message.", "Use a separate publishing tool if you need to schedule Instagram content itself."], links },
    ]),
  "how-to-capture-leads-using-instagram-and-export-to-excel": guide("Collect Instagram Leads and Export Contacts to CSV", "Use AP3K Collect Email or Collect Phone, verify the saved contact, then export filtered leads on Pro or Business.", "contacts",
    "A useful lead export starts with a clear reason to collect the information. In AP3K, Pro and Business can collect an email address or phone number during a supported conversation and export Contacts as CSV. This walkthrough covers the recipient path, saved record and spreadsheet checks.", [
      { heading: "Ask for information that serves the request", paragraphs: ["Choose a specific offer: an emailed guide, consultation follow-up or product enquiry. Explain why an email or phone number is needed and what happens afterward. Receiving a resource and consenting to ongoing marketing are different choices; do not assume one automatically grants the other.", "Build the comment, story or incoming-DM trigger that matches how the person contacts you. On an eligible paid plan, add Collect Email or Collect Phone in the supported editor step. Replace placeholder questions, confirmations and destination links with your actual business wording."], screenshot: "collect-email" },
      { heading: "Test the collection step end to end", paragraphs: ["Publish the reviewed flow and run it from another Instagram account. Complete any opener or follow request before answering the collection prompt. Verify the final message arrives when the required information is accepted.", "Test an invalid response as well as a valid one. Check that the flow asks again or follows the configured behavior rather than treating arbitrary text as verified contact information. Then open Contacts in the same selected Instagram account and confirm the expected email or phone is on the correct contact."], screenshot: "collect-phone" },
      { heading: "Filter before downloading", paragraphs: ["Open Contacts and use the Last interacted on, Created on, Email and Phone filters to choose the relevant group. A date filter helps separate the current campaign from older contacts. Select Download CSV on Pro or Business; Free does not include export.", "Open the file in your spreadsheet application using its CSV import flow. Keep phone numbers as text so leading zeros and country prefixes are preserved. Check row counts, empty fields and duplicates before importing the data into another system. Export only the fields and contacts you need."], screenshot: "contacts" },
      { heading: "Measure lead quality, not only volume", paragraphs: ["A captured contact is not a confirmed sale or booking. Record which campaign generated the interaction and use your destination system to measure the next outcome. For example, compare valid enquiry contacts with completed appointments rather than calling every email a conversion.", "If information is missing, inspect the conversation and automation activity. The person may not have completed the prompt, the message may be waiting for an opener, or the wrong Instagram account may be selected in Contacts. Re-exporting cannot recover information that was never supplied."], links: [{ label: "Collection setup documentation", href: "/docs/post-automation/collect-email-and-phone-number-in-dm" }] },
      { heading: "Handle the file responsibly", paragraphs: ["A CSV is a copy of customer information outside AP3K. Share it only with people who need it for the stated purpose and follow your retention and consent practices. Do not put private contacts into public examples or the general AI Knowledge section.", "If you want an external integration, verify the supported mechanism rather than assuming that a CSV export is an automatic sync. AP3K does not provide native Zapier contact-event subscriptions; explicit Flow webhooks are a separate capability that requires its own configuration and testing."], links: [{ label: "Review privacy and deletion choices", href: "/privacy" }, ...links] },
    ]),
  "how-to-set-up-instagram-dm-automation-using-ap3k": guide("Set Up an Incoming Instagram DM Automation in AP3K", "Create an incoming-DM trigger, write a useful response and test keyword matching without confusing it with a comment campaign.", "chat",
    "An incoming-DM automation responds after a person messages your Instagram account. It is different from a comment-to-DM campaign, which starts under a post. Use Chat automation when your audience sends a word such as PRICE or BOOK directly to your inbox.", [
      { heading: "Choose the correct account and source", paragraphs: ["Connect an Instagram Business or Creator account and verify DMs ready. Select the intended Instagram account in AP3K before creating the automation. A campaign saved under another profile will not respond to messages arriving in this inbox.", "Open Automations and create a Chat or DM automation. Choose a keyword rule for a specific request, or an any-message rule only when the response is appropriate for every eligible incoming message. Avoid using a broad trigger simply because a narrow one has not been tested yet."], screenshot: "chat" },
      { heading: "Write an answer that completes the request", paragraphs: ["For PRICE, give the relevant price or a clear route to the current offer. For BOOK, explain the next step and add your real booking destination. Use a link label that describes the destination, stays within 20 characters and matches the promise in your Instagram bio or post.", "Keep the first version short. Adding a collection step, follow gate or branch before checking basic delivery creates several possible failure points. Test a fixed reply first, then add the paid features that improve the conversation."], links: [{ label: "DM message formats and buttons", href: "/docs/post-automation/dm-message-layouts-text-buttons-attachments" }] },
      { heading: "Use AI only when it adds useful flexibility", paragraphs: ["A fixed message is predictable for one keyword and one destination. AI is better suited to varied questions when your Knowledge contains accurate answers. Pro and Business include monthly AI allowances; Free does not include live AI replies.", "Before enabling AI in the intended automation, add your prices, products, policies and escalation destination. Test a normal question, an unknown question and an attempt to demand an unauthorized discount. Playground tests the response logic but does not prove real Instagram delivery."], screenshot: "ai-knowledge" },
      { heading: "Verify positive and negative paths", paragraphs: ["Review and publish the automation, then send a fresh matching message from another Instagram account. Confirm the correct response and open its link. Test a non-matching message to make sure a keyword-only rule does not catch unrelated requests.", "Check activity when the result differs from the preview. Inspect the selected account, Live state, trigger, usage and messaging readiness. Another app controlling the conversation can affect delivery. Repeatedly editing the response text will not resolve an authorization error."], links: [{ label: "Troubleshoot incoming DM replies", href: "/docs/troubleshoot/fix-auto-reply-not-sending-in-dms" }] },
      { heading: "Keep follow-ups within the conversation", paragraphs: ["A follow-up must be eligible under Instagram’s messaging rules and the configured condition at the time it runs. Do not describe the automation as permission to send an unlimited sequence. A paused flow, new inbound message or closed window can change what should happen next.", "Keep a short test record with the account, trigger text, expected response and observed result. That makes later troubleshooting more precise when several campaigns use similar words. Review a few real conversations after launch. Make it easy for a person with an unexpected question to reach your team, and keep changes focused on the points where people get stuck. Helpful automation completes the person’s request; sending more messages is not the goal."], links },
    ]),
  "grow-followers": guide("Use an Instagram Follow Request Without Hiding the Offer", "Plan an honest AP3K follow-gate journey, test both follow states and measure completion rather than promising follower growth.", "follow-gate",
    "An Ask to follow step can request that someone follow your account before receiving the final resource. It adds friction as well as an opportunity for a continuing relationship. Use it when the resource and future content justify the request, not as a guarantee of follower growth.", [
      { heading: "Decide whether a gate helps the customer", paragraphs: ["A person who asks for basic product information may not expect another requirement before receiving it. For a resource offered in exchange for a follow, make that condition clear in the caption. Avoid a post that promises an immediate link while the DM introduces an undisclosed requirement.", "Start with a useful, specific resource and a reason to keep following. ‘Get the checklist and future examples’ is clearer than a vague growth promise. The wording is an illustrative campaign idea, not a claim about customer results."], links: [{ label: "Ask to follow documentation", href: "/docs/post-automation/ask-to-follow-before-sending-dm" }] },
      { heading: "Build the opener, request and final delivery", paragraphs: ["In an eligible Pro or Business automation, review the opening DM, the follow request and the final DM as one recipient journey. The continuation button begins the interaction; the follow verification determines whether the next gated step can proceed.", "The final message should deliver exactly what the post offered. Add the real link with a short descriptive label. Keep public acknowledgement separate from private delivery so the comment does not imply the resource arrived before it actually did."], screenshot: "follow-gate" },
      { heading: "Test both states", paragraphs: ["Use a controlled second account to test the path before following and again after completing the requested action. Verify how the follow check behaves and whether the final resource is delivered. Do not test only the first bubble in the phone preview.", "If verification does not progress, check the account, connection readiness, interaction and available follow-status signal. Do not repeatedly send unrelated messages to force the flow. Inspect the recorded result and ask support about a persistent mismatch."], screenshot: "message" },
      { heading: "Measure the tradeoff", paragraphs: ["Track how many eligible people enter the flow, complete the interaction and reach the promised destination. A larger entry count with poor completion can mean the gate is too demanding or the offer is unclear. A follow is not a purchase, and a sent DM is not proof of either.", "Compare one clearly defined change at a time, such as the offer wording or whether the gate is necessary. Keep the post, audience and measurement period in mind when interpreting results. Small tests are directional evidence, not guaranteed outcomes."], links: [{ label: "Campaign measurement guide", href: "/blog/comment-to-dm-ab-testing" }] },
      { heading: "Limits remain in force", paragraphs: ["Ask to follow does not authorize arbitrary bulk messaging, bypass Instagram rules or promise immunity from restrictions. Follow-ups still need messaging eligibility, and every successfully sent public reply or DM uses the relevant allowance.", "Make the final destination accessible on mobile and confirm that its content matches the original promise. If the resource requires another signup, disclose that requirement before someone completes a follow request. Avoid stacking several unexpected gates after the initial comment. If the campaign can meet its goal with a direct link, that simpler route may be better. Keep the gate only when it serves a clear business purpose and the customer understands the exchange."], links },
    ]),
};
