import { BUTTON_LABEL_GUIDE } from "./button-label-guide";
import type { BlogPost } from "../blog";

/** Substantive editorial revisions keep existing URLs, not duplicate SEO pages. */
export const SEO_REVISIONS: Record<string, Partial<BlogPost>> = {
  "comment-to-dm-button-labels": BUTTON_LABEL_GUIDE,
  "instagram-comment-to-dm-automation": {
    importedArchive: false,
    title: "Instagram Comment-to-DM Automation: Setup and Testing",
    seoTitle: "Instagram Comment-to-DM Automation Guide | AP3K",
    description: "Set up Instagram comment-to-DM automation in AP3K: choose a post, match a keyword, send your link and test delivery with a practical checklist.",
    subtitle: "A practical AP3K walkthrough for delivering a promised link after an Instagram comment, with a test plan and troubleshooting steps.",
    updatedAt: "2026-10-05",
    readingTime: "6 min read",
    category: "Instagram Automation",
    contentLocale: "en",
    cover: "automations",
    wordCount: undefined,
    keywords: ["Instagram comment-to-DM automation", "Instagram comment triggers", "AP3K tutorial"],
    intro: "Instagram comment-to-DM automation sends a configured private response when an eligible comment matches your rule. In AP3K, a Post automation can send a public reply, a DM, or both. Start with one post and one useful destination so you can verify the whole conversation before expanding it.",
    sections: [
      { heading: "Choose the right automation for the interaction", paragraphs: ["Use a Post automation when someone comments on a post or Reel. Story replies belong in Story automation, while a keyword sent directly to your inbox belongs in Chat automation. Choosing the wrong entry point can leave an otherwise correct message waiting for an event it will never receive.", "This guide covers an inbound comment journey, not bulk unsolicited messaging. It is published by AP3K about its own product; the examples below are illustrative setups, not customer results."], links: [{label: "Compare Instagram comment-to-DM features", href: "/instagram-comment-to-dm"}, {label: "Explore other Instagram DM triggers", href: "/instagram-dm-automation"}] },
      { heading: "Connect the account and choose the post", screenshot: "instagram-ready", paragraphs: ["Connect an Instagram Business or Creator account that you are authorized to manage. Check the selected username before creating the automation, especially when your workspace contains more than one account. Comments and DMs have separate readiness requirements.", "Create a Post automation and select the post or Reel that contains your offer. For a first test, use one specific post rather than an account-wide rule. Keep the caption, keyword and destination together so later edits do not make the post promise something different from the DM."], links: [{label: "Follow the Instagram connection guide", href: "/blog/connect-instagram-to-ap3k"}] },
      { heading: "Match a keyword to a clear offer", paragraphs: ["A keyword rule is useful when the caption says, for example, ‘Comment GUIDE for the checklist.’ Enter GUIDE in the trigger settings. Any comment is a different choice: it covers eligible comments regardless of whether they request your resource. Use it deliberately, not as a workaround for a broken keyword.", "Write the smallest useful response first. Example caption: ‘Comment GUIDE and I’ll send the checklist.’ Example public reply: ‘Thanks! Look out for the guide in your DMs.’ Example DM: ‘Here is the checklist you requested.’ Add a Get the Guide button pointing to your actual HTTPS destination. These are sample messages; replace them before publishing."], links: [{label: "Compare keyword and any-comment rules", href: "/blog/instagram-comment-automation-keyword-vs-any-comment"}] },
      { heading: "Configure the DM and optional steps", paragraphs: ["Enable Send a DM and review the destination on mobile. A public comment reply is optional and does not prove that the private message was delivered. If you enable both actions, test both separately.", "An opener, follow request, contact-collection step or follow-up changes the customer journey. Add these only when they serve your offer, and check your plan’s eligibility. A follow gate adds another step before delivery, so do not test only the first visible message. Keep AI-generated replies grounded in accurate business information and review them before publishing."], links: [{label: "Read the complete Post automation setup", href: "/docs/post-automation/create-instagram-comment-to-dm-automation"}, {label: "Compare current AP3K plans and allowances", href: "/pricing"}] },
      { heading: "Publish and run a real delivery test", screenshot: "automations", paragraphs: ["The phone preview checks the wording and sequence; it is not a delivery receipt from Instagram. Publish the automation, then use another Instagram account to leave a fresh comment. Test once with the configured keyword and once with unrelated text so you verify both the positive and negative paths."], bullets: ["Confirm the correct Instagram account, post and Live status.", "Leave a fresh matching comment after activation; confirm the public reply when enabled.", "Open the receiving account’s inbox and message requests to check the DM.", "Open the button destination and complete every optional step in the flow.", "Check AP3K activity for successful, failed or skipped actions. Do not equate every run with a lead or sale."], links: [{label: "Watch the AP3K comment-to-DM video tutorial", href: "/tutorials/instagram-comment-to-dm"}] },
      { heading: "Diagnose a missing message one stage at a time", paragraphs: ["If no rule runs, start with the account, selected post, Live status and trigger text. If the public reply appears but the DM does not, inspect DM readiness, message permissions and the recorded failure rather than rewriting the caption. If another optional step is waiting for input, complete that step from the receiving account.", "A duplicate-protection setting can intentionally skip repeated interactions from the same person. Use a fresh test interaction that meets the saved rule rather than repeatedly replaying the same event. Check your usage allowance and the destination URL before changing several settings at once. Instagram delivery still depends on account permissions and platform rules."], links: [{label: "Troubleshoot Instagram comment and DM delivery", href: "/docs/troubleshoot/fix-comment-automation-not-working"}, {label: "Contact AP3K support with the account and automation details", href: "/contact"}] },
      { heading: "Treat older comments as a separate backtracking task", paragraphs: ["Publishing an automation does not automatically replay the post’s entire comment history. AP3K’s separate Backtrack comments control can review eligible comments from the previous seven days for a supported selected-media automation. It applies the saved rule and normal delivery protections; it is not permission to contact every past commenter.", "Use View media to confirm the post, review the current rule, then start backtracking deliberately. A matching comment can still be skipped or fail because of duplicates, account restrictions, usage or Instagram delivery rules. Check the result rather than assuming every older comment received a DM."] },
      { heading: "Measure the outcome, then expand", paragraphs: ["Choose a campaign outcome before adding more posts: a requested guide delivered, a relevant email captured, a booking completed or a purchase. Those are different stages. Use a tagged destination URL and your destination analytics to connect visits with bookings or purchases instead of describing sent-message counts as revenue.", "For a simple usage illustration, 200 people each receiving one public reply and one DM generate 400 successfully sent actions. Extra messages add actions. This example is arithmetic, not a forecast, and plan allowances should be checked on the pricing page. Once the full path works, reuse the tested setup for another relevant post."], links: [{label: "Plan a comment-to-DM campaign", href: "/instagram-comment-to-dm"}, {label: "Compare AP3K and ManyChat for Instagram", href: "/manychat-alternative"}] },
    ],
  },
};
export const SEO_REVISED_SLUGS = new Set(Object.keys(SEO_REVISIONS));
