import Link from "next/link";
import { ArrowUpRight, Clapperboard, CirclePlay, MessageCircle } from "lucide-react";
import { UiText } from "@/components/i18n/localized-copy";
export default function QuickStart({ slug }: { slug: string }) {
  return <section aria-labelledby="quick-start-title" className="ap3k-content-enter"><div className="mb-3 flex items-center justify-between gap-3"><h2 id="quick-start-title" className="text-sm font-bold text-slate-700 dark:text-slate-200"><UiText>What would you like to automate?</UiText></h2><Link href={`/dashboard/${slug}/automation/new`} className="text-xs font-semibold text-violet-700 dark:text-violet-300"><UiText>View all</UiText></Link></div><div className="grid gap-3 sm:grid-cols-3">{[
    {type:"comment",title:"Post automation",subtitle:"Replies when someone comments on a post or reel",icon:Clapperboard,color:"from-violet-500 to-blue-500"},
    {type:"story",title:"Story automation",subtitle:"Replies to story replies and reactions",icon:CirclePlay,color:"from-fuchsia-500 to-violet-500"},
    {type:"dm",title:"Chat automation",subtitle:"Replies to keywords sent in DMs",icon:MessageCircle,color:"from-orange-400 to-pink-500"},
  ].map(({type,title,subtitle,icon:Icon,color})=><Link key={type} href={`/dashboard/${slug}/automation/new?type=${type}`} className="group flex min-w-0 flex-col items-start gap-4 rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm transition-[border-color,transform,box-shadow] duration-200 hover:border-violet-400 hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-violet-500 motion-safe:hover:-translate-y-0.5 dark:border-white/10 dark:bg-[#111320]"><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-[18px] bg-gradient-to-br text-white ${color}`}><Icon className="h-7 w-7" aria-hidden="true" /></span><span className="flex w-full items-start gap-2"><span className="min-w-0 flex-1"><span className="block text-lg font-semibold"><UiText>{title}</UiText></span><span className="mt-1 block text-xs leading-5 text-slate-500 dark:text-slate-400"><UiText>{subtitle}</UiText></span></span><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-slate-400" aria-hidden="true" /></span></Link>)}</div></section>;
}
