import {describe,expect,it,vi} from "vitest";
import {fetchActiveInstagramStories} from "./instagram-stories";
const now=Date.parse("2026-10-04T09:00:00Z");
const integration={token:"TEST_ONLY_not_a_real_token",instagramId:"business",igAccountSource:"instagram_login"};
const media=(id="1",age=3600000)=>({id,timestamp:new Date(now-age).toISOString(),media_url:`https://cdn.test/${id}.jpg`,media_type:"IMAGE"});
const response=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status});
describe("Instagram active stories fetch",()=>{
 it("uses /me/stories for Instagram Login, not /media or a messaging-scoped ID",async()=>{const fetcher=vi.fn().mockResolvedValue(response({data:[media()]}));const result=await fetchActiveInstagramStories(integration,{now,fetcher});expect(result).toMatchObject({ok:true,complete:true,stories:[{id:"1"}]});const [url,options]=fetcher.mock.calls[0];expect(url).toMatch(/^https:\/\/graph.instagram.com\/v[^/]+\/me\/stories\?/);expect(url).not.toContain(integration.token);expect(options.headers.Authorization).toBe(`Bearer ${integration.token}`);expect(options.cache).toBe("no-store");});
 it("uses the business ID on Facebook Login",async()=>{const fetcher=vi.fn().mockResolvedValue(response({data:[]}));await fetchActiveInstagramStories({...integration,igAccountSource:"facebook_login"},{now,fetcher});expect(fetcher.mock.calls[0][0]).toMatch(/^https:\/\/graph.facebook.com\/v[^/]+\/business\/stories/);});
 it("filters expired rows and returns true empty state only on a successful list",async()=>{const fetcher=vi.fn().mockResolvedValue(response({data:[media("expired",86400000)]}));expect(await fetchActiveInstagramStories(integration,{now,fetcher})).toMatchObject({ok:true,stories:[]});});
 it("follows cursor pagination without forwarding credentials to an API-provided host",async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response({data:[media("1")],paging:{next:"https://untrusted.test/steal",cursors:{after:"cursor-two"}}})).mockResolvedValueOnce(response({data:[media("2")]}));const result=await fetchActiveInstagramStories(integration,{now,fetcher});expect(result.stories).toHaveLength(2);expect(fetcher.mock.calls[1][0]).toContain("graph.instagram.com");expect(fetcher.mock.calls[1][0]).toContain("after=cursor-two");});
 it.each([190,10,200])("distinguishes authorization error %s from an empty story tray",async code=>{const fetcher=vi.fn().mockResolvedValue(response({error:{code,message:"secret details"}},400));const result=await fetchActiveInstagramStories(integration,{now,fetcher});expect(result).toMatchObject({ok:false,complete:false,reconnectRequired:true});expect(JSON.stringify(result)).not.toContain("secret details");});
 it("returns a rate-limit error, not no-stories",async()=>{const fetcher=vi.fn().mockResolvedValue(response({error:{code:4}},429));expect(await fetchActiveInstagramStories(integration,{now,fetcher})).toMatchObject({ok:false,reconnectRequired:false,error:expect.stringContaining("limiting")});});
 it("rejects incomplete metadata rather than silently selecting the wrong next story",async()=>{const fetcher=vi.fn().mockResolvedValue(response({data:[media(),{id:"broken"}]}));expect(await fetchActiveInstagramStories(integration,{now,fetcher})).toMatchObject({ok:false,complete:false,stories:[{id:"1"}]});});
 it("does not use a partial page set for next-story binding",async()=>{const fetcher=vi.fn().mockResolvedValue(response({data:[media()],paging:{next:"https://graph.instagram.com/next",cursors:{after:"cursor"}}}));expect(await fetchActiveInstagramStories(integration,{now,fetcher,maxPages:1})).toMatchObject({ok:false,complete:false});});
 it("handles malformed data, cursor loops, network errors and a disconnected account",async()=>{for(const value of [{},{data:null},{data:[],paging:{next:"somewhere"}}])expect((await fetchActiveInstagramStories(integration,{now,fetcher:vi.fn().mockResolvedValue(response(value))})).ok).toBe(false);const loop=vi.fn().mockResolvedValue(response({data:[media()],paging:{next:"x",cursors:{after:"same"}}}));expect((await fetchActiveInstagramStories(integration,{now,fetcher:loop})).ok).toBe(false);expect(loop).toHaveBeenCalledTimes(2);expect((await fetchActiveInstagramStories(integration,{now,fetcher:vi.fn().mockRejectedValue(new Error("network"))})).ok).toBe(false);const disconnected=vi.fn();expect(await fetchActiveInstagramStories({}, {now,fetcher:disconnected})).toMatchObject({ok:false,reconnectRequired:true});expect(disconnected).not.toHaveBeenCalled();});
});
