/** Small shared feature index. Text retrieval stays server-side in support-knowledge. */
export type SupportResource = { id: string; title: string; href: string; dashboard?: string; screenshot?: string; video?: boolean; terms: string[]; facts?: string };
export const SUPPORT_RESOURCES: SupportResource[] = [
  {id:"connect",title:"Connect Instagram",href:"/docs/getting-started/connect-instagram-account",dashboard:"account",screenshot:"account",terms:["connect","permission","reconnect","ربط","connexion"],facts:"Use a Business or Creator account. Open Manage account and inspect Comments ready and DMs ready. Reconnect repairs access; removing an account deletes its AP3K data."},
  {id:"comment",title:"Create a Post automation",href:"/docs/post-automation/create-instagram-comment-to-dm-automation",dashboard:"automation/new?type=comment",screenshot:"trigger",video:true,terms:["comment","keyword","trigger","any comment","تعليق","كلمة","mot clé"],facts:"Post automations handle post/Reel comments. Choose keyword or any comment, then public reply, DM or both. One DM per user can intentionally skip repeats. Shares are a separate optional trigger where offered, not proof the sharer commented."},
  {id:"message",title:"DM messages and link buttons",href:"/docs/post-automation/dm-message-layouts-text-buttons-attachments",dashboard:"automation",screenshot:"message",video:true,terms:["button","link","final dm","label","رابط","bouton"],facts:"Final DM link buttons have separate label and URL fields. Labels have a 20-character limit; up to three link buttons. A phone preview does not verify real delivery."},
  {id:"opener",title:"Opening DM",href:"/docs/post-automation/opener-message-before-sending-the-link",dashboard:"automation",screenshot:"opening",terms:["opening","opener","first message","افتتاح"]},
  {id:"follow",title:"Ask to follow",href:"/docs/post-automation/ask-to-follow-before-sending-dm",dashboard:"automation",screenshot:"follow",terms:["follow gate","ask to follow","i followed","متابعة","abonn"],facts:"Pro/Business follow gates ask non-followers to follow and tap I followed. The check must pass before the final DM; a tap alone is not proof of following."},
  {id:"followup",title:"Follow-up messages",href:"/docs/post-automation/send-follow-up-messages-with-conditions",dashboard:"automation",screenshot:"follow-up",terms:["follow-up","follow up","delay","تأخير","relance"],facts:"Follow-ups require Pro/Business and respect the saved condition, timing and Meta messaging eligibility. Delays on different steps are independent. A delayed send is not guaranteed if messaging eligibility expires."},
  {id:"capture",title:"Collect Email and Collect Phone",href:"/docs/post-automation/collect-email-and-phone-number-in-dm",dashboard:"contacts",screenshot:"collect",terms:["email","phone","capture","collect","بريد","هاتف","téléphone"],facts:"Pro/Business only. Enable the requested fields; the recipient must provide a valid answer. Invalid answers retry rather than completing capture. Email and phone update the same contact. Review Contacts and Download CSV."},
  {id:"contacts",title:"Contacts and CSV export",href:"/help/contacts-leads",dashboard:"contacts",screenshot:"contacts",terms:["contact","csv","export","filter","جهات","تصدير"],facts:"Contacts supports Last interacted on, Created on, Email and Phone filters. Download CSV requires Pro/Business; it exports contacts matching the selected filters. Contacts are not confirmed sales."},
  {id:"story",title:"Story automation",href:"/docs/story-automation/create-instagram-story-automation",dashboard:"automation/new?type=story",screenshot:"story",terms:["story","stories","ستوري","قصة"],facts:"Story automations react to supported Story replies, reactions or mentions. They do not run on a passive view. Story media can expire; check the selected account and active-story picker."},
  {id:"dm",title:"Chat / DM automation",href:"/docs/chat-automation/create-a-chat-automation",dashboard:"automation/new?type=dm",screenshot:"chat",terms:["chat","incoming","dm automation","رسالة","محادثة"]},
  {id:"flow",title:"Flow Builder",href:"/docs/flow-builder/wiring-basics",dashboard:"automation/new",screenshot:"flow",terms:["flow","canvas","branch","node","مسار"],facts:"The Flow Builder connects triggers, messages, conditions and supported actions. AI-assisted drafts must be reviewed. Free can generate drafts/samples but publishing a custom Flow requires a paid plan. Never claim a draft was saved or published by support."},
  {id:"ai",title:"AI replies, Knowledge and Behavior",href:"/help/ai-knowledge",dashboard:"ai",screenshot:"ai-knowledge",terms:["ai","knowledge","tone","protection","ذكاء","معرفة"],facts:"AI replies require Pro/Business; generation of samples is separate from live publishing. Knowledge stores approved business facts; Behavior controls tone and protections. Playground tests do not automatically update live knowledge."},
  {id:"safety",title:"AI Meta Policy Safety Check",href:"/docs/how-tos/ai-meta-policy-safety-check",dashboard:"automation",screenshot:"safety",terms:["safety","policy","scan","meta","سياسة","فحص"],facts:"Available before publishing to review risk patterns. Free has three scans; Pro/Business has unlimited scans subject to technical rate limits. This is guidance, not Meta approval or a delivery guarantee. Scanning does not publish an automation."},
  {id:"backtrack",title:"Backtrack comments",href:"/docs/how-tos/backtrack-comments-in-automation",dashboard:"automation",screenshot:"backtrack",terms:["backtrack","past comments","old comments","تعليقات قديمة"],facts:"A deliberate operation for eligible comments from the previous seven days on supported selected media. Free has three attempts; paid plans unlimited attempts, with normal delivery and usage protections. View media first. Backtracking sends real messages and must not be started by support automatically."},
  {id:"analytics",title:"Dashboard and analytics",href:"/help/workspace-tour",dashboard:"",screenshot:"dashboard",terms:["analytic","metric","performance","report","تحليل","إحصائيات"],facts:"Dashboard periods and per-automation analytics describe recorded activity. Followers, leads, runs and successful sends are different metrics. A contact or sent message is not proof of revenue."},
  {id:"templates",title:"Automation templates",href:"/docs/post-automation/post-automation-templates",dashboard:"automation/new",screenshot:"templates",terms:["template","preset","قالب","نموذج"]},
  {id:"billing",title:"Plans and usage",href:"/pricing",dashboard:"billing",terms:["plan","billing","price","free","pro","business","limit","اشتراك","مجاني","سعر"],facts:"Plan limits and prices come from the current product configuration below. Support cannot charge, cancel, refund or change a plan. Open Billing to review actual subscription status."},
  {id:"delivery",title:"Public reply sent, but no DM",href:"/docs/troubleshoot/fix-public-reply-sent-but-no-dm",dashboard:"account",terms:["not sent","not working","missing","failed","no dm","لا تصل","ne fonctionne"],facts:"Check the connected account, Live status, trigger, DM permissions, duplicate rules, waiting steps and usage. Test from another Instagram account and inspect inbox/message requests. Never claim to have checked the user's delivery records."},
];
export function selectSupportResources(message: string, previousQuestion = ""): SupportResource[] {
  const text = message.toLowerCase();
  const selected = SUPPORT_RESOURCES.map(resource => ({resource, score: resource.terms.reduce((score, term) => {
    // Short aliases must be words: "email" must not accidentally select "AI".
    const match = /^[a-z]{1,3}$/.test(term) ? new RegExp(`\\b${term}\\b`).test(text) : text.includes(term);
    return score + (match ? term.length : 0);
  }, 0)}))
    .filter(item => item.score > 0).sort((a,b) => b.score-a.score).slice(0,3).map(item => item.resource);
  return selected.length || !previousQuestion ? selected : selectSupportResources(previousQuestion);
}
