import type { BlogPost } from "./blog";

// Keep source copy in English so changing locale always starts from the same text.
export const TUTORIAL_ARABIC_COPY: Record<string, string> = {};
function copy(en: string, ar: string) { TUTORIAL_ARABIC_COPY[en] = ar; return en; }

export const TUTORIAL_LABELS = {
  enlarge: copy("Enlarge screenshot", "تكبير الصورة"),
  original: copy("Open full-size image", "فتح الصورة بالحجم الكامل"),
  zoom: copy("Zoom in", "تكبير"),
  fit: copy("Fit to screen", "ملاءمة الشاشة"),
  hint: copy("Tap any screenshot to enlarge it. Screens show an example account; your activity and available plan details may differ.", "اضغط على أي صورة لتكبيرها. الصور تعرض حسابًا كمثال، وقد تختلف أرقام حسابك وتفاصيل خطتك."),
  guides: copy("Learn AP3K with real screenshots", "تعلّم استخدام AP3K بالصور"),
  read: copy("Read the illustrated guide", "اقرأ الشرح بالصور"),
  category: copy("Illustrated tutorials", "شروحات بالصور"),
  pan: copy("Zoom in, then scroll across the image to read the details.", "كبّر الصورة ثم مرّر داخلها لقراءة التفاصيل."),
};

export const TUTORIAL_SCREENSHOTS = {
  dashboard: { height: 980, title: copy("Home dashboard", "لوحة التحكم الرئيسية"), caption: copy("Home shows the connected account, date filters, performance totals, and active automations.", "تعرض الصفحة الرئيسية الحساب المتصل وفترة الإحصاءات والنتائج والردود التلقائية النشطة.") },
  "automation-types": { height: 980, title: copy("Choose an automation type", "اختر نوع الرد التلقائي"), caption: copy("Choose Comment automation, Story automation, or DM automation according to where the interaction starts.", "اختر ردود التعليقات أو القصص أو الرسائل الخاصة حسب المكان الذي يبدأ فيه التفاعل.") },
  automations: { height: 980, title: copy("Manage automations", "إدارة الردود التلقائية"), caption: copy("The automation list shows each flow's channel, trigger, actions, runs, leads, and Live or Paused status.", "تعرض القائمة نوع كل رد تلقائي وشرط تشغيله وإجراءاته وعدد مرات تشغيله والعملاء المهتمين وحالته.") },
  contacts: { height: 980, title: copy("Contacts and conversation sources", "جهات الاتصال ومصدر المحادثة"), caption: copy("Search contacts by Instagram username. Open chat is available when a conversation exists; Lead captured is a different state.", "ابحث باسم المستخدم في إنستغرام. يظهر خيار فتح المحادثة عند وجود محادثة، أما تسجيل عميل مهتم فهو حالة مختلفة.") },
  "ai-overview": { height: 980, title: copy("AI Overview and readiness", "نظرة عامة على المساعد الذكي"), caption: copy("Overview separates business knowledge, voice and behavior, and the AI Replies and AI Comments master switches.", "تفصل صفحة النظرة العامة بين معلومات نشاطك وأسلوب الرد ومفتاحي تشغيل الردود الذكية للرسائل والتعليقات.") },
  "ai-knowledge": { height: 980, title: copy("AI Knowledge notes", "معلومات نشاطك للمساعد الذكي"), caption: copy("Add a Topic and Facts AI may use. Saved notes appear in the panel beside the form.", "أضف عنوانًا ومعلومات يمكن للمساعد استخدامها. تظهر الملاحظات المحفوظة بجانب النموذج.") },
  "ai-behavior": { height: 980, title: copy("AI voice, tone, and guardrails", "أسلوب المساعد وحدود الرد"), caption: copy("Behavior contains the AI role, brand voice, tone, guardrails, and comment-protection settings.", "تضم صفحة السلوك دور المساعد وأسلوب علامتك ونبرة الرد وحدوده وإعدادات التعامل مع التعليقات.") },
  "ai-playground": { height: 980, title: copy("Test in AI Playground", "جرّب المساعد قبل تشغيله"), caption: copy("Playground asks for at least one knowledge note before a meaningful test. Tests count toward the monthly AI limit.", "أضف معلومة واحدة على الأقل قبل التجربة في مساحة الاختبار. تُحتسب التجارب ضمن حد استخدام الذكاء الاصطناعي الشهري.") },
  inbox: { height: 980, title: copy("Instagram Inbox conversations", "محادثات إنستغرام"), caption: copy("Inbox has conversation search, a chat list, the selected thread, and a manual reply composer.", "يضم صندوق الوارد البحث وقائمة المحادثات والرسائل وخانة كتابة رد يدوي.") },
  billing: { height: 1284, title: copy("Billing and monthly usage", "الاشتراك والاستخدام الشهري"), caption: copy("Billing separates automated actions, AI replies, and active automations. The screenshot shows an example Business subscription.", "تعرض صفحة الفوترة الإجراءات التلقائية وردود الذكاء الاصطناعي والردود التلقائية النشطة بشكل منفصل. الصورة مثال على اشتراك الأعمال.") },
  referrals: { height: 1244, title: copy("Referral link and reward progress", "رابط الدعوة ومتابعة المكافآت"), caption: copy("Refer & earn shows your personal invite link, qualification steps, reward totals, and referral activity.", "تعرض صفحة الدعوات رابطك الخاص وشروط الحصول على المكافأة ورصيدك وحالة الأشخاص الذين دعوتهم.") },
  settings: { height: 1163, title: copy("Appearance, email, and account settings", "المظهر والبريد وإعدادات الحساب"), caption: copy("Settings groups theme, sign-in management, optional email preferences, and permanent account deletion.", "تجمع الإعدادات المظهر وإدارة تسجيل الدخول وتفضيلات البريد الاختيارية وحذف الحساب نهائيًا.") },
} as const;
export type TutorialScreenshotId = keyof typeof TUTORIAL_SCREENSHOTS;
export function tutorialImageSrc(id: TutorialScreenshotId) { return `/images/tutorials/${id}.png`; }

const base = {
  publishedAt: "2026-09-20", updatedAt: "2026-09-20", category: TUTORIAL_LABELS.category,
  readingTime: "8 min read", visual: "workflow" as const,
  visualAlt: "AP3K workflow connecting Instagram interactions with replies and direct messages",
  visualCaption: "Follow the real AP3K workspace screens alongside the instructions in this guide.",
};

export const ILLUSTRATED_POSTS: BlogPost[] = [
  {
    ...base, slug: "ap3k-workspace-visual-guide", cover: "dashboard",
    title: copy("Your AP3K Workspace: A Complete Visual Guide", "دليل استخدام لوحة تحكم AP3K بالصور"),
    description: copy("Explore the AP3K dashboard, automations, contacts, Inbox, billing, referrals, and settings with real screenshots and practical instructions.", "تعرّف بالصور على لوحة تحكم AP3K والردود التلقائية وجهات الاتصال والرسائل والاشتراك والدعوات والإعدادات، مع خطوات واضحة للاستخدام."),
    keywords: ["AP3K tutorial", "AP3K dashboard", "Instagram automation"],
    intro: copy("Use this tour to find your way around AP3K after connecting Instagram. Start with Home, check your automations, then follow the conversation through Contacts and Inbox. The final sections explain your subscription and account controls.", "بعد ربط إنستغرام، ابدأ بالصفحة الرئيسية وتابع ردودك التلقائية، ثم تعرّف على جهات الاتصال وصندوق الوارد. وفي نهاية الدليل ستجد شرحًا للاشتراك وإعدادات الحساب."),
    sections: [
      { heading: copy("1. Read your Home dashboard", "1. تعرّف على الصفحة الرئيسية"), screenshot: "dashboard", paragraphs: [copy("Check the Instagram username at the top before reading the results. Use Last 24h, Last 7d, This month, or Last 30d to choose the reporting period. Followers, Posts, Comments, Leads, and Replies describe different parts of your activity; leads are not confirmed purchases.", "تأكد أولًا من اسم حساب إنستغرام أعلى الصفحة، ثم اختر فترة الإحصاءات: آخر 24 ساعة أو 7 أيام أو الشهر الحالي أو آخر 30 يومًا. ستجد المتابعين والمنشورات والتعليقات والعملاء المهتمين والردود. تسجيل عميل مهتم لا يعني أنه اشترى.")], bullets: [copy("Use the account selector in the sidebar when you manage more than one Instagram profile.", "استخدم قائمة الحسابات في الشريط الجانبي للتبديل بين حسابات إنستغرام."), copy("Manage account opens the connection controls. View all opens the full automation list.", "يفتح زر إدارة الحساب إعدادات الاتصال، ويفتح عرض الكل قائمة الردود التلقائية.")] },
      { heading: copy("2. Find and manage an automation", "2. ابحث عن رد تلقائي وأدره"), screenshot: "automations", paragraphs: [copy("Open Automations from the sidebar. Search by automation name, keyword, or content, then use the sort menu to organize the list. Read the Trigger and Actions columns together: a keyword decides when a flow starts, while the actions describe what it sends.", "افتح الردود التلقائية من القائمة الجانبية. ابحث بالاسم أو الكلمة المحددة أو المحتوى، واستخدم قائمة الترتيب. يوضح شرط التشغيل متى يبدأ الرد التلقائي، وتوضح الإجراءات ما الذي سيرسله.")], bullets: [copy("Edit opens the configuration. Pause stops a live flow; Start resumes a paused flow.", "يفتح تعديل إعدادات الرد. يوقف إيقاف مؤقت الرد النشط، ويعيد بدء تشغيل الرد المتوقف."), copy("Runs and Leads are separate counters. Create Automation starts a new flow.", "عدد مرات التشغيل وعدد العملاء المهتمين إحصاءان مختلفان. لإنشاء رد جديد، اختر إنشاء رد تلقائي.")] },
      { heading: copy("3. Find people in Contacts", "3. ابحث عن الأشخاص في جهات الاتصال"), screenshot: "contacts", paragraphs: [copy("Open Contacts and search by Instagram username. The Source column helps distinguish comment interactions from manual conversations. Choose Open chat when it is available to continue in Inbox. A Lead captured label records the interaction; it does not mean a manual conversation is available or a sale is complete.", "افتح جهات الاتصال وابحث باسم المستخدم في إنستغرام. يوضح عمود المصدر هل جاء الشخص من تعليق أم محادثة يدوية. اختر فتح المحادثة عندما يكون متاحًا. عبارة تسجيل عميل مهتم لا تعني وجود محادثة يدوية أو إتمام عملية شراء.")] },
      { heading: copy("4. Continue a conversation in Inbox", "4. تابع المحادثة في صندوق الوارد"), screenshot: "inbox", paragraphs: [copy("Search conversations, select a person in the chat list, and read the thread before replying. The selected conversation shows its source and previous messages. Write in the reply box and choose Send; Enter sends and Shift + Enter starts a new line. Use Refresh if recent activity is missing.", "ابحث عن المحادثة واختر الشخص من القائمة، ثم اقرأ الرسائل السابقة قبل الرد. اكتب ردك واضغط إرسال. يرسل زر Enter الرسالة، ويضيف Shift + Enter سطرًا جديدًا. استخدم التحديث إذا لم تظهر رسالة حديثة."), copy("Manual replies depend on the Instagram connection and messaging eligibility. A contact entry alone does not guarantee that you can send a message.", "يتطلب الرد اليدوي اتصالًا سليمًا بإنستغرام وإمكانية إرسال الرسالة وفق قواعده. وجود جهة اتصال وحده لا يضمن إمكانية مراسلتها.")] },
      { heading: copy("5. Check your plan and usage", "5. راجع اشتراكك واستخدامك"), screenshot: "billing", paragraphs: [copy("Open Billing to see your current plan, subscription status, renewal date, and usage. Automated actions and AI replies have separate allowances. One successful public reply or DM counts as one action; sending both uses two, and additional messages use additional actions. Playground tests count toward the AI allowance.", "افتح الفوترة لمراجعة خطتك وحالة اشتراكك وموعد التجديد والاستخدام. للإجراءات التلقائية وردود الذكاء الاصطناعي حدود منفصلة. كل رد عام أو رسالة خاصة ناجحة تُحسب إجراءً واحدًا؛ وإرسال الاثنين يُحسب إجراءين. وتُحتسب تجارب المساعد ضمن رصيد الذكاء الاصطناعي."), copy("Use the Monthly or Annual selector when comparing plans. Paid subscribers use Manage or cancel subscription to open the billing portal. Read the current details in your own workspace rather than treating the example screenshot's balance, price, or renewal date as your account information.", "بدّل بين الشهري والسنوي عند مقارنة الخطط. لإدارة اشتراك مدفوع أو إلغائه، افتح بوابة الفوترة من الزر المخصص. اعتمد على التفاصيل الظاهرة في حسابك؛ فالأرقام والأسعار والتواريخ في الصورة تخص الحساب المعروض كمثال.")] },
      { heading: copy("6. Track invitations in Refer & earn", "6. تابع الدعوات والمكافآت"), screenshot: "referrals", paragraphs: [copy("Copy your own invite link from Refer & earn and share it with a friend. The three stages are a new signup through your link, connecting Instagram, and an eligible paid subscription. Follow the progress cards and referral activity to see which stage each invitation has reached.", "انسخ رابط الدعوة الخاص بك وشاركه مع صديق. تمر الدعوة بثلاث مراحل: إنشاء حساب جديد من رابطك، ثم ربط إنستغرام، ثم اشتراك مدفوع يستوفي الشروط. تابع البطاقات وقائمة الدعوات لمعرفة حالة كل دعوة."), copy("Read Eligibility and rules before expecting a reward. The illustrated Founding 10 offer gives qualifying credit toward a future invoice; copying a link or getting a signup alone does not earn that credit. Use your own link, not the one pictured here.", "اقرأ شروط الأهلية قبل توقع المكافأة. يمنح عرض Founding 10 المعروض رصيدًا لفاتورة قادمة عند استيفاء الشروط؛ نسخ الرابط أو التسجيل وحده لا يمنح الرصيد. استخدم رابط حسابك أنت، وليس الرابط الظاهر في الصورة.")] },
      { heading: copy("7. Set appearance, email, and account preferences", "7. اضبط المظهر والبريد والحساب"), screenshot: "settings", paragraphs: [copy("In Settings, choose Light or Dark under Appearance. Manage sign-in settings opens your authentication controls. Under Email notifications, select the optional messages you want and choose Save email preferences. Essential security, connection, usage, support, and billing emails remain enabled.", "في الإعدادات، اختر المظهر الفاتح أو الداكن. افتح إدارة تسجيل الدخول لتعديل إعدادات الدخول. وفي إشعارات البريد، حدد الرسائل الاختيارية التي تريدها ثم احفظ التفضيلات. تظل رسائل الأمان والاتصال والاستخدام والدعم والفوترة الأساسية مفعّلة."), copy("The Danger zone is for permanent account deletion, including automations, Instagram data, leads, and the sign-in account. To pause an automation, use Pause in Automations instead of deleting your account.", "منطقة الخطر مخصصة لحذف الحساب نهائيًا، بما فيه الردود التلقائية وبيانات إنستغرام والعملاء المهتمون وحساب الدخول. إذا أردت إيقاف رد تلقائي فقط، استخدم إيقاف مؤقت من قائمة الردود التلقائية.")] },
    ],
  },
  {
    ...base, slug: "create-ap3k-automation-visual-guide", cover: "automation-types",
    title: copy("Create an AP3K Automation: Comments, Stories, and DMs", "إنشاء رد تلقائي في AP3K للتعليقات والقصص والرسائل"),
    description: copy("Choose the right AP3K automation type, configure a comment or message trigger, review your replies, and check the live flow with this visual guide.", "اختر نوع الرد التلقائي المناسب في AP3K، وحدد متى يبدأ وما الذي يرسله، ثم راجع الرسائل واختبر النتيجة باتباع هذا الدليل المصور."),
    keywords: ["AP3K tutorial", "Instagram comment automation", "Instagram DM automation"],
    intro: copy("An automation starts with an interaction, checks your trigger, and runs the actions you enabled. Begin with one clear goal: deliver a requested link, acknowledge a comment, or answer an incoming message. Connect the intended professional Instagram account before building the flow.", "يبدأ الرد التلقائي بتفاعل من شخص، ثم يتحقق من الشرط الذي حددته وينفذ الإجراءات التي فعّلتها. ابدأ بهدف واضح: إرسال رابط مطلوب، أو الرد على تعليق، أو الإجابة عن رسالة. اربط حساب إنستغرام الاحترافي المطلوب قبل البدء."),
    sections: [
      { heading: copy("1. Choose where the conversation starts", "1. اختر أين تبدأ المحادثة"), screenshot: "automation-types", paragraphs: [copy("Open Automations, choose Create Automation, then select Build this flow on the appropriate card. These are three different starting points, not three stages of the same automation.", "افتح الردود التلقائية واضغط إنشاء رد تلقائي، ثم اختر بناء هذا التدفق من البطاقة المناسبة. هذه ثلاثة أنواع مختلفة لبداية الرد، وليست مراحل متتالية لرد واحد.")], bullets: [copy("Comment automation: a comment on a post or Reel can trigger a public reply, a DM, or both.", "ردود التعليقات: يمكن لتعليق على منشور أو ريلز أن يبدأ ردًا عامًا أو رسالة خاصة أو الاثنين."), copy("Story automation: choose the supported story interaction, such as a mention, emoji reaction, or text reply.", "ردود القصص: اختر التفاعل المدعوم، مثل الإشارة إلى حسابك أو التفاعل برمز تعبيري أو الرد النصي."), copy("DM automation: respond to a new incoming message containing a keyword, or to any eligible message.", "ردود الرسائل الخاصة: أجب عن رسالة جديدة تحتوي على كلمة محددة، أو عن أي رسالة تستوفي الشروط.")] },
      { heading: copy("2. Set the trigger and write the response", "2. حدد شرط التشغيل واكتب الرد"), paragraphs: [copy("For a comment flow, name the automation, choose its post scope, and select Specific keyword or Any comment. If your caption asks people to comment GUIDE, configure that keyword. Turn on Reply to comment, Send a DM, or both, then replace sample messages with your own copy.", "في ردود التعليقات، سمّ الرد واختر المنشور أو نطاق المنشورات، ثم اختر كلمة محددة أو أي تعليق. إذا طلبت من الناس كتابة GUIDE، أضف هذه الكلمة. فعّل الرد على التعليق أو إرسال رسالة خاصة أو الاثنين، واستبدل النصوص التجريبية برسائلك."), copy("For a story or DM flow, choose the relevant interaction or message rule in its builder, then write the response and any link buttons. Story and DM flows respond privately; they are not public comment replies.", "في ردود القصص أو الرسائل، اختر التفاعل أو شرط الرسالة من صفحة الإعداد، ثم اكتب الرد وأضف أزرار الروابط عند الحاجة. هذه الردود تُرسل على الخاص وليست تعليقات عامة.")], bullets: [copy("Opening DM is optional in a comment flow. Leave it off when you want to send the final DM directly.", "الرسالة الافتتاحية اختيارية في ردود التعليقات. اتركها متوقفة إذا أردت إرسال الرسالة النهائية مباشرة."), copy("If you enable a follow request or another optional step, test that complete path before publishing.", "إذا فعّلت طلب المتابعة أو أي خطوة اختيارية، اختبر المسار كاملًا قبل النشر."), copy("Check every button label and destination URL. The final DM supports up to three labeled links.", "راجع اسم كل زر ورابطه. تدعم الرسالة النهائية حتى ثلاثة روابط بأسماء واضحة.")] },
      { heading: copy("3. Preview, publish, and test", "3. راجع وانشر واختبر"), paragraphs: [copy("Use the builder's phone preview to read the experience as a customer. Check the selected account, trigger, enabled actions, messages, and links, then publish. Test with a fresh, eligible interaction from another Instagram account after activation. For a comment flow, verify the public reply and DM separately.", "استخدم معاينة الهاتف لترى التجربة كما يراها العميل. راجع الحساب والشرط والإجراءات والرسائل والروابط، ثم انشر. بعد التشغيل، اختبر بتفاعل جديد يستوفي الشروط من حساب إنستغرام آخر. وفي ردود التعليقات، تحقق من الرد العام والرسالة الخاصة كلٍّ على حدة."), copy("If a reply is missing, confirm the flow is Live, the interaction matches the saved rule, the Instagram connection is ready, and your usage allowance is available. Correct one issue and test with a new interaction.", "إذا لم يصل الرد، تأكد من أن الحالة نشطة، وأن التفاعل يطابق الشرط المحفوظ، وأن اتصال إنستغرام سليم ورصيد الاستخدام متاح. أصلح المشكلة ثم اختبر بتفاعل جديد.")] },
      { heading: copy("4. Review the live automation", "4. تابع الرد التلقائي بعد تشغيله"), screenshot: "automations", paragraphs: [copy("Return to Automations and find the new flow. Confirm the channel, trigger, enabled actions, and Live status. Watch Runs and Leads as interactions arrive. Use Edit to change the setup or Pause to stop it. Check Inbox for the resulting conversation and Home for the wider account totals.", "ارجع إلى الردود التلقائية وابحث عن الرد الجديد. راجع نوعه وشرطه وإجراءاته وحالته النشطة. تابع مرات التشغيل والعملاء المهتمين مع وصول التفاعلات. استخدم تعديل لتغيير الإعدادات أو إيقاف مؤقت لإيقافه. ستجد المحادثة في صندوق الوارد والإحصاءات العامة في الصفحة الرئيسية.")] },
    ],
  },
  {
    ...base, slug: "set-up-ap3k-ai-visual-guide", cover: "ai-overview", visual: "workflow",
    title: copy("Set Up AP3K AI: Knowledge, Behavior, and Playground", "إعداد مساعد AP3K الذكي: المعلومات والأسلوب والتجربة"),
    description: copy("Set up AP3K AI with a four-screen tutorial: review readiness, add business knowledge, choose behavior, and test answers before enabling live replies.", "أعدّ مساعد AP3K الذكي في أربع خطوات مصورة: راجع الجاهزية، وأضف معلومات نشاطك، واختر أسلوب الرد، واختبر الإجابات قبل تشغيلها."),
    keywords: ["AP3K tutorial", "AP3K AI", "Instagram AI replies"],
    intro: copy("Open AI Assistant in the sidebar to reach AP3K AI. The four tabs form a practical setup sequence: Overview, Knowledge, Behavior, and Playground. Prepare and test your answers before enabling AI in selected automations. AI features require a plan that includes them.", "افتح المساعد الذكي من القائمة الجانبية. ستجد أربع صفحات: نظرة عامة، ومعلومات النشاط، والسلوك، ومساحة التجربة. أضف المعلومات واختبر الردود قبل تفعيلها في الردود التلقائية التي تختارها. تتطلب هذه الميزات خطة تشمل الذكاء الاصطناعي."),
    sections: [
      { heading: copy("1. Review readiness in Overview", "1. راجع الجاهزية في النظرة العامة"), screenshot: "ai-overview", paragraphs: [copy("Read Your AI readiness to see what remains to prepare. Open knowledge takes you to business facts; Open behavior takes you to voice and response rules. AI Replies controls DM replies and AI Comments controls comment replies at workspace level.", "راجع جاهزية المساعد لمعرفة ما تبقى من الإعداد. افتح المعلومات لإضافة حقائق عن نشاطك، وافتح السلوك لضبط أسلوب الرد. يتحكم مفتاح ردود الرسائل الذكية في الرسائل الخاصة، ويتحكم مفتاح التعليقات الذكية في التعليقات على مستوى مساحة العمل."), copy("These are master switches. Each automation must also opt into AI, so switching on a skill does not automatically convert every saved flow. Use Save changes after editing the configuration.", "هذه مفاتيح تشغيل عامة. يجب أيضًا تفعيل الذكاء الاصطناعي داخل كل رد تلقائي تريده، فلا تتحول كل الردود المحفوظة تلقائيًا إلى ردود ذكية. اضغط حفظ التغييرات بعد التعديل.")] },
      { heading: copy("2. Add reliable business knowledge", "2. أضف معلومات صحيحة عن نشاطك"), screenshot: "ai-knowledge", paragraphs: [copy("In Knowledge, give each note a clear Topic and fill in Facts AI may use. Choose Add knowledge, check that the note appears under Saved knowledge, and save your changes. Keep separate notes for services, prices, delivery, policies, and frequently asked questions so updates stay simple.", "في صفحة المعلومات، اكتب عنوانًا واضحًا لكل ملاحظة وأضف الحقائق التي يمكن للمساعد استخدامها. اضغط إضافة معلومة، وتأكد من ظهورها في المعلومات المحفوظة، ثم احفظ التغييرات. خصص ملاحظات منفصلة للخدمات والأسعار والتوصيل والسياسات والأسئلة الشائعة لتسهيل تحديثها."), copy("Use exact, current facts and say what the assistant should do when information is unknown. The empty state in the screenshot means no knowledge has been added yet. Do not add passwords, payment details, or private customer information.", "استخدم معلومات دقيقة وحديثة، ووضح للمساعد ما يفعله عندما لا تتوفر الإجابة. الحالة الفارغة في الصورة تعني عدم إضافة معلومات بعد. لا تضف كلمات مرور أو بيانات دفع أو معلومات خاصة بالعملاء.")] },
      { heading: copy("3. Choose voice and response boundaries", "3. اختر أسلوب الرد وحدوده"), screenshot: "ai-behavior", paragraphs: [copy("In Behavior, describe the AI role and your brand voice. Choose Fun, Friendly, or Professional as the default tone. In Guardrails & escalation, explain when to avoid guessing and when to offer human help. Keep these instructions consistent with your saved business facts.", "في صفحة السلوك، حدد دور المساعد وأسلوب علامتك. اختر نبرة مرحة أو ودودة أو مهنية. وفي حدود الرد والتحويل للدعم، وضح متى يتجنب المساعد التخمين ومتى يعرض المساعدة البشرية. اجعل التعليمات متوافقة مع معلومات نشاطك."), copy("Review Comment protection deliberately. Skip reply and Delete are different actions: deleting affects the Instagram comment. The screenshot shows a Delete selection for insults and hate speech as an example, not a required setting. Choose what suits your moderation policy, then save.", "راجع حماية التعليقات بعناية. تجاهل الرد وحذف التعليق إجراءان مختلفان؛ الحذف يؤثر على التعليق في إنستغرام. تعرض الصورة اختيار الحذف للإهانات كمثال وليس كإعداد مطلوب. اختر ما يناسب سياسة إدارة تعليقاتك ثم احفظ.")] },
      { heading: copy("4. Test in Playground before going live", "4. اختبر المساعد قبل تشغيله"), screenshot: "ai-playground", paragraphs: [copy("Add at least one knowledge note, save the setup, then ask a realistic customer question in Playground. Try a follow-up and a question your notes do not answer. Check accuracy, tone, and whether the assistant respects your boundaries. Update Knowledge or Behavior and test again if needed.", "أضف معلومة واحدة على الأقل واحفظ الإعدادات، ثم اطرح سؤالًا واقعيًا كما لو كنت عميلًا. جرّب سؤال متابعة وسؤالًا لا تجيب عنه معلوماتك. راجع دقة الرد وأسلوبه والتزامه بالحدود، وعدّل المعلومات أو السلوك ثم أعد التجربة عند الحاجة."), copy("Playground conversations are saved, but they do not become live business knowledge automatically. Save useful facts explicitly as knowledge. Tests use your monthly AI allowance. When the results are ready, enable the appropriate master switch and AI option in the intended automation, save, and test the live flow.", "تُحفظ محادثات التجربة، لكنها لا تصبح معلومات معتمدة للنشاط تلقائيًا. احفظ الحقائق المفيدة صراحةً ضمن المعلومات. تُحتسب التجارب ضمن رصيد الذكاء الاصطناعي الشهري. عندما تصبح النتائج مناسبة، فعّل المفتاح العام وخيار الذكاء الاصطناعي في الرد التلقائي المطلوب، ثم احفظ واختبره.")] },
    ],
  },
];

// Attach the same reviewed screenshots to the matching knowledge-base topics.
export const HELP_TUTORIALS: Record<string, { screenshots: TutorialScreenshotId[]; guide: string }> = {
  "workspace-tour": { screenshots: ["dashboard"], guide: "ap3k-workspace-visual-guide" },
  "automation-types": { screenshots: ["automation-types"], guide: "create-ap3k-automation-visual-guide" },
  "create-automation": { screenshots: ["automations"], guide: "create-ap3k-automation-visual-guide" },
  "ai-setup": { screenshots: ["ai-overview"], guide: "set-up-ap3k-ai-visual-guide" },
  "ai-knowledge": { screenshots: ["ai-knowledge", "ai-playground"], guide: "set-up-ap3k-ai-visual-guide" },
  "ai-safety": { screenshots: ["ai-behavior"], guide: "set-up-ap3k-ai-visual-guide" },
  "contacts-leads": { screenshots: ["contacts"], guide: "ap3k-workspace-visual-guide" },
  inbox: { screenshots: ["inbox"], guide: "ap3k-workspace-visual-guide" },
  "plans-usage": { screenshots: ["billing"], guide: "ap3k-workspace-visual-guide" },
  "refer-earn": { screenshots: ["referrals"], guide: "ap3k-workspace-visual-guide" },
  "privacy-delete": { screenshots: ["settings"], guide: "ap3k-workspace-visual-guide" },
};
