import { LOCALE_SOURCE_COLUMN, SUPPORTED_LOCALES, type Locale } from "./config";

const rows = [
  ["Your Instagram account changed. Reload this page before saving.", "Votre compte Instagram a changé. Rechargez cette page avant d’enregistrer.", "Tu cuenta de Instagram ha cambiado. Recarga esta página antes de guardar.", "Dein Instagram-Konto wurde gewechselt. Lade diese Seite vor dem Speichern neu.", "A sua conta do Instagram mudou. Recarregue esta página antes de guardar."],
  ["Up to 3 Instagram accounts", "Jusqu’à 3 comptes Instagram", "Hasta 3 cuentas de Instagram", "Bis zu 3 Instagram-Konten", "Até 3 contas do Instagram"],
  ["Up to 10 Instagram accounts", "Jusqu’à 10 comptes Instagram", "Hasta 10 cuentas de Instagram", "Bis zu 10 Instagram-Konten", "Até 10 contas do Instagram"],
  ["Free includes 1 Instagram account, Pro includes 3, and Business includes 10. Each account has separate automations, contacts, inbox, analytics, and AI knowledge. Monthly reply and AI allowances are shared across your subscription.", "L’offre Free comprend 1 compte Instagram, Pro en comprend 3 et Business 10. Chaque compte dispose de ses propres automatisations, contacts, boîte de réception, statistiques et connaissances IA. Les quotas mensuels de réponses et d’IA sont partagés entre les comptes de votre abonnement.", "Free incluye 1 cuenta de Instagram, Pro incluye 3 y Business incluye 10. Cada cuenta tiene sus propias automatizaciones, contactos, bandeja de entrada, analíticas y conocimientos de IA. Los límites mensuales de respuestas y de IA se comparten entre las cuentas de tu suscripción.", "Free enthält 1 Instagram-Konto, Pro 3 und Business 10. Jedes Konto hat eigene Automatisierungen, Kontakte, einen eigenen Posteingang, Analysen und KI-Wissen. Die monatlichen Antwort- und KI-Kontingente gelten gemeinsam für alle Konten deines Abonnements.", "O Free inclui 1 conta do Instagram, o Pro inclui 3 e o Business inclui 10. Cada conta tem as suas próprias automações, contactos, caixa de entrada, análises e conhecimentos de IA. Os limites mensais de respostas e de IA são partilhados entre as contas da sua subscrição."],
  ["Monthly reply and AI allowances are shared across your subscription.", "Les quotas mensuels de réponses et d’IA sont partagés entre les comptes de votre abonnement.", "Los límites mensuales de respuestas y de IA se comparten entre las cuentas de tu suscripción.", "Die monatlichen Antwort- und KI-Kontingente gelten gemeinsam für alle Konten deines Abonnements.", "Os limites mensais de respostas e de IA são partilhados entre as contas da sua subscrição."],
  ["Removing this Instagram account permanently deletes only its automations, contacts, inbox, analytics, and AI knowledge. Your other accounts stay unchanged.", "Supprimer ce compte Instagram efface définitivement ses automatisations, contacts, messages, statistiques et connaissances IA. Vos autres comptes restent inchangés.", "Eliminar esta cuenta de Instagram borra permanentemente sus automatizaciones, contactos, mensajes, analíticas y conocimientos de IA. Tus otras cuentas no cambian.", "Beim Entfernen dieses Instagram-Kontos werden nur dessen Automatisierungen, Kontakte, Nachrichten, Analysen und KI-Wissen dauerhaft gelöscht. Deine anderen Konten bleiben unverändert.", "Remover esta conta do Instagram elimina permanentemente apenas as suas automações, contactos, mensagens, análises e conhecimentos de IA. As suas outras contas permanecem inalteradas."],
  ["Reconnect or add an Instagram account", "Reconnecter ou ajouter un compte Instagram", "Reconectar o añadir una cuenta de Instagram", "Instagram-Konto erneut verbinden oder hinzufügen", "Voltar a ligar ou adicionar uma conta do Instagram"],
  ["Reconnecting restores the same account. Use the account menu to add another account; existing accounts and automations stay unchanged.", "La reconnexion rétablit le même compte. Utilisez le menu des comptes pour en ajouter un autre ; vos comptes et automatisations existants restent inchangés.", "La reconexión restaura la misma cuenta. Usa el menú de cuentas para añadir otra; las cuentas y automatizaciones existentes no cambian.", "Eine erneute Verbindung stellt dasselbe Konto wieder her. Füge über das Kontomenü ein weiteres Konto hinzu; vorhandene Konten und Automatisierungen bleiben unverändert.", "Voltar a ligar restabelece a mesma conta. Use o menu de contas para adicionar outra; as contas e automações existentes permanecem inalteradas."],
  ["Your Instagram account limit has been reached. Upgrade your plan to connect more accounts.", "Vous avez atteint la limite de comptes Instagram. Choisissez une offre supérieure pour en connecter davantage.", "Has alcanzado el límite de cuentas de Instagram. Mejora tu plan para conectar más cuentas.", "Du hast dein Instagram-Kontolimit erreicht. Verbinde mit einem höheren Tarif weitere Konten.", "Atingiu o limite de contas do Instagram. Melhore o plano para ligar mais contas."],
] as const;

export const ACCOUNT_PLAN_COPY = Object.fromEntries(SUPPORTED_LOCALES.map((locale) => [locale, Object.fromEntries(rows.map((row) => [row[0], row[LOCALE_SOURCE_COLUMN[locale]]]))])) as Record<Locale, Record<string, string>>;
