import type { Locale } from "./config";
export const MARKETING_PRIVACY_COPY: Record<Locale, Record<string, string>> = {
  "en": {},
  "fr": {
    "Optional Launch-Kit Emails": "E-mails facultatifs du kit de lancement",
    "When you request our launch-kit email series, we store your email address, selected audience, signup page, consent version, confirmation time, and subscription status. We use this information to send the requested kit and two follow-up lessons through Resend, including an invitation to try AP3K. We also retain delivery records and unsubscribe or suppression records to honor your choices. Confirming this series does not subscribe you to an ongoing newsletter. Every email includes an unsubscribe link requiring no login. Contact support@ap3k.com to request access or deletion. Rate-limit identifiers are hashed to help prevent abuse.": "Lorsque vous demandez notre série d’e-mails du kit de lancement, nous conservons votre adresse e-mail, le public sélectionné, la page d’inscription, la version du consentement, la date de confirmation et le statut de l’abonnement. Ces informations servent à envoyer le kit demandé et deux leçons complémentaires via Resend, avec une invitation à essayer AP3K. Nous conservons aussi les données de livraison, de désinscription et de suppression pour respecter vos choix. Confirmer cette série ne vous abonne pas à une newsletter régulière. Chaque e-mail contient un lien de désinscription sans connexion. Contactez support@ap3k.com pour demander l’accès ou la suppression de vos données. Les identifiants de limitation des requêtes sont hachés pour prévenir les abus.",
    "AP3K uses service providers including Meta for Instagram access, Clerk for authentication, Stripe for billing, Neon for database hosting, Vercel for application hosting, Resend for service emails and requested marketing emails, and configured AI providers when AI features are enabled. Each provider processes only the information needed for its role.": "AP3K utilise notamment Meta pour l’accès à Instagram, Clerk pour l’authentification, Stripe pour la facturation, Neon pour l’hébergement des données, Vercel pour l’hébergement de l’application, Resend pour les e-mails de service et les e-mails marketing demandés, ainsi que les fournisseurs d’IA configurés lorsque ces fonctions sont activées. Chaque prestataire ne traite que les informations nécessaires à son rôle."
  },
  "es": {
    "Optional Launch-Kit Emails": "Correos opcionales del kit de lanzamiento",
    "When you request our launch-kit email series, we store your email address, selected audience, signup page, consent version, confirmation time, and subscription status. We use this information to send the requested kit and two follow-up lessons through Resend, including an invitation to try AP3K. We also retain delivery records and unsubscribe or suppression records to honor your choices. Confirming this series does not subscribe you to an ongoing newsletter. Every email includes an unsubscribe link requiring no login. Contact support@ap3k.com to request access or deletion. Rate-limit identifiers are hashed to help prevent abuse.": "Cuando solicitas nuestra serie de correos del kit de lanzamiento, guardamos tu dirección de correo, el público seleccionado, la página de registro, la versión del consentimiento, la fecha de confirmación y el estado de la suscripción. Usamos estos datos para enviar el kit solicitado y dos lecciones de seguimiento mediante Resend, incluida una invitación a probar AP3K. También conservamos registros de entrega, baja y supresión para respetar tus preferencias. Confirmar esta serie no te suscribe a un boletín continuo. Cada correo incluye un enlace de baja sin iniciar sesión. Contacta con support@ap3k.com para solicitar acceso o eliminación. Los identificadores usados para limitar solicitudes se almacenan mediante hash para prevenir abusos.",
    "AP3K uses service providers including Meta for Instagram access, Clerk for authentication, Stripe for billing, Neon for database hosting, Vercel for application hosting, Resend for service emails and requested marketing emails, and configured AI providers when AI features are enabled. Each provider processes only the information needed for its role.": "AP3K utiliza proveedores como Meta para acceder a Instagram, Clerk para la autenticación, Stripe para la facturación, Neon para alojar la base de datos, Vercel para alojar la aplicación, Resend para correos de servicio y marketing solicitado, y los proveedores de IA configurados cuando se activan esas funciones. Cada proveedor trata únicamente la información necesaria para su función."
  },
  "de": {
    "Optional Launch-Kit Emails": "Optionale E-Mails zum Startpaket",
    "When you request our launch-kit email series, we store your email address, selected audience, signup page, consent version, confirmation time, and subscription status. We use this information to send the requested kit and two follow-up lessons through Resend, including an invitation to try AP3K. We also retain delivery records and unsubscribe or suppression records to honor your choices. Confirming this series does not subscribe you to an ongoing newsletter. Every email includes an unsubscribe link requiring no login. Contact support@ap3k.com to request access or deletion. Rate-limit identifiers are hashed to help prevent abuse.": "Wenn du unsere E-Mail-Serie zum Startpaket anforderst, speichern wir deine E-Mail-Adresse, die gewählte Zielgruppe, die Anmeldeseite, die Einwilligungsversion, den Bestätigungszeitpunkt und den Abonnementstatus. Wir nutzen diese Angaben, um das angeforderte Paket und zwei weitere Lektionen über Resend zu senden, einschließlich einer Einladung, AP3K auszuprobieren. Wir bewahren auch Zustellungs-, Abmelde- und Sperrvermerke auf, um deine Entscheidungen zu beachten. Die Bestätigung dieser Serie meldet dich nicht für einen dauerhaften Newsletter an. Jede E-Mail enthält einen Abmeldelink ohne Anmeldung. Für Auskunft oder Löschung kontaktiere support@ap3k.com. Kennungen zur Begrenzung von Anfragen werden zum Schutz vor Missbrauch gehasht.",
    "AP3K uses service providers including Meta for Instagram access, Clerk for authentication, Stripe for billing, Neon for database hosting, Vercel for application hosting, Resend for service emails and requested marketing emails, and configured AI providers when AI features are enabled. Each provider processes only the information needed for its role.": "AP3K nutzt unter anderem Meta für den Instagram-Zugang, Clerk für die Authentifizierung, Stripe für die Abrechnung, Neon für das Datenbankhosting, Vercel für das Anwendungshosting, Resend für Service-E-Mails und angeforderte Marketing-E-Mails sowie konfigurierte KI-Anbieter bei aktivierten KI-Funktionen. Jeder Anbieter verarbeitet nur die für seine Aufgabe erforderlichen Informationen."
  },
  "pt": {
    "Optional Launch-Kit Emails": "E-mails opcionais do kit de lançamento",
    "When you request our launch-kit email series, we store your email address, selected audience, signup page, consent version, confirmation time, and subscription status. We use this information to send the requested kit and two follow-up lessons through Resend, including an invitation to try AP3K. We also retain delivery records and unsubscribe or suppression records to honor your choices. Confirming this series does not subscribe you to an ongoing newsletter. Every email includes an unsubscribe link requiring no login. Contact support@ap3k.com to request access or deletion. Rate-limit identifiers are hashed to help prevent abuse.": "Quando solicita a nossa série de e-mails do kit de lançamento, guardamos o endereço de e-mail, o público selecionado, a página de inscrição, a versão do consentimento, a data de confirmação e o estado da subscrição. Usamos estes dados para enviar o kit solicitado e duas lições adicionais através do Resend, incluindo um convite para experimentar o AP3K. Conservamos também registos de entrega, cancelamento e supressão para respeitar as suas escolhas. Confirmar esta série não subscreve uma newsletter contínua. Cada e-mail inclui uma ligação para cancelar sem iniciar sessão. Contacte support@ap3k.com para pedir acesso ou eliminação dos dados. Os identificadores de limitação de pedidos são guardados como hashes para prevenir abusos.",
    "AP3K uses service providers including Meta for Instagram access, Clerk for authentication, Stripe for billing, Neon for database hosting, Vercel for application hosting, Resend for service emails and requested marketing emails, and configured AI providers when AI features are enabled. Each provider processes only the information needed for its role.": "O AP3K utiliza fornecedores como a Meta para acesso ao Instagram, Clerk para autenticação, Stripe para faturação, Neon para alojamento da base de dados, Vercel para alojamento da aplicação, Resend para e-mails de serviço e marketing solicitado, e os fornecedores de IA configurados quando essas funções estão ativas. Cada fornecedor trata apenas as informações necessárias à sua função."
  }
};
