import type { Locale } from "./config";

type ProductCatalog = Record<string, string>;

const en: ProductCatalog = {};

const ar: ProductCatalog = {
  "Automations": "عمليات الأتمتة", "Inbox": "صندوق الوارد", "Contacts": "جهات الاتصال", "AI Replies": "ردود الذكاء الاصطناعي", "Account": "الحساب", "Billing": "الفوترة", "Settings": "الإعدادات", "Help": "المساعدة", "Referrals": "الإحالات", "Integrations": "عمليات الربط",
  "Create automation": "إنشاء أتمتة", "+ New automation": "+ أتمتة جديدة", "+ Create Automation": "+ إنشاء أتمتة", "Create your first automation": "أنشئ أول أتمتة", "No automations yet": "لا توجد عمليات أتمتة بعد", "Active automations": "عمليات الأتمتة النشطة", "Recent activity": "النشاط الأخير", "Performance": "الأداء", "View all": "عرض الكل", "Welcome back,": "مرحبًا بعودتك،",
  "Continue": "متابعة", "Back": "رجوع", "Save": "حفظ", "Saving...": "جارٍ الحفظ...", "Save as draft": "حفظ كمسودة", "Cancel": "إلغاء", "Close": "إغلاق", "Refresh": "تحديث", "Preview": "معاينة", "Optional": "اختياري", "Monthly": "شهري", "Annual": "سنوي", "Current plan": "الخطة الحالية", "Manage billing": "إدارة الفوترة", "Upgrade": "ترقية", "Upgrade to Pro": "الترقية إلى Pro",
  "Connect Instagram": "ربط إنستغرام", "Reconnect Instagram": "إعادة ربط إنستغرام", "Instagram connected": "تم ربط إنستغرام", "Instagram not connected": "إنستغرام غير متصل", "Remove connection": "إزالة الربط", "Manage connection": "إدارة الربط", "Connection health": "حالة الاتصال", "Permission readiness": "جاهزية الأذونات", "Your Instagram": "حسابك على إنستغرام", "Instagram performance": "أداء إنستغرام",
  "Choose a post or Reel": "اختر منشورًا أو ريلز", "Choose a specific post or Reel": "اختر منشورًا أو ريلز محددًا", "Any post": "أي منشور", "Specific keyword": "كلمة مفتاحية محددة", "What comment starts this automation?": "ما التعليق الذي يبدأ هذه الأتمتة؟", "What should AP3K do?": "ماذا تريد من AP3K أن يفعل؟", "Reply to comment": "الرد على التعليق", "Send a DM": "إرسال رسالة خاصة", "Opening DM": "الرسالة الافتتاحية", "DM with links": "رسالة خاصة مع روابط", "Follow request DM": "رسالة طلب المتابعة", "Optional follow request": "طلب متابعة اختياري", "Review & Activate": "مراجعة وتفعيل", "Active automation": "أتمتة نشطة", "Go live": "تفعيل الآن",
  "Automation name": "اسم الأتمتة", "Add link": "إضافة رابط", "Button label": "نص الزر", "Destination URL": "رابط الوجهة", "Opening message": "الرسالة الافتتاحية", "DM message text": "نص الرسالة الخاصة", "Add words that trigger automation": "أضف الكلمات التي تشغّل الأتمتة", "No keywords": "لا توجد كلمات مفتاحية", "Search posts": "البحث في المنشورات", "No Posts Found": "لم يتم العثور على منشورات", "Show all posts": "عرض كل المنشورات", "Close preview": "إغلاق المعاينة", "Edit automation": "تعديل الأتمتة", "Back to automations": "العودة إلى الأتمتة",
  "All chats": "كل المحادثات", "Unread": "غير مقروء", "Recent": "الأحدث", "Search conversations": "البحث في المحادثات", "Open chat": "فتح المحادثة", "Message…": "اكتب رسالة…", "Add emoji": "إضافة رمز تعبيري", "Send": "إرسال", "Updates automatically": "يُحدّث تلقائيًا", "No messages in this conversation yet.": "لا توجد رسائل في هذه المحادثة بعد.", "Search contacts": "البحث في جهات الاتصال", "Search by Instagram username": "البحث باسم مستخدم إنستغرام", "Instagram contact": "جهة اتصال إنستغرام", "Source": "المصدر",
  "AP3K AI": "ذكاء AP3K الاصطناعي", "AI Comments": "تعليقات الذكاء الاصطناعي", "Knowledge base": "قاعدة المعرفة", "Add knowledge": "إضافة معلومة", "Saved knowledge": "المعلومات المحفوظة", "Behavior": "السلوك", "Comment protection": "حماية التعليقات", "Ask a customer-style question": "اطرح سؤالًا كعميل", "Send test": "إرسال اختبار", "Thinking…": "جارٍ التفكير…", "Save changes": "حفظ التغييرات", "Upgrade to enable AI comments, AI DM replies, knowledge, and the playground.": "قم بالترقية لتفعيل تعليقات ورسائل الذكاء الاصطناعي وقاعدة المعرفة وساحة الاختبار.",
  "Preferences": "التفضيلات", "Appearance": "المظهر", "Account & authentication": "الحساب وتسجيل الدخول", "Email notifications": "إشعارات البريد الإلكتروني", "Save email preferences": "حفظ تفضيلات البريد", "Delete account permanently": "حذف الحساب نهائيًا", "This action cannot be undone.": "لا يمكن التراجع عن هذا الإجراء.", "Keep my account": "الاحتفاظ بحسابي", "Cookie preferences": "تفضيلات ملفات تعريف الارتباط", "Accept analytics": "قبول التحليلات", "Your privacy, your choice": "خصوصيتك، خيارك", "Get help": "الحصول على المساعدة", "Email support": "مراسلة الدعم", "How can we help?": "كيف يمكننا مساعدتك؟", "Search AP3K help…": "ابحث في مساعدة AP3K…", "Ask a question…": "اطرح سؤالًا…", "Try again": "حاول مجددًا",
};

const fr: ProductCatalog = {
  "Automations": "Automatisations", "Inbox": "Boîte de réception", "Contacts": "Contacts", "AI Replies": "Réponses IA", "Account": "Compte", "Billing": "Facturation", "Settings": "Paramètres", "Help": "Aide", "Referrals": "Parrainages", "Integrations": "Intégrations",
  "Create automation": "Créer une automatisation", "+ New automation": "+ Nouvelle automatisation", "+ Create Automation": "+ Créer une automatisation", "Create your first automation": "Créez votre première automatisation", "No automations yet": "Aucune automatisation", "Active automations": "Automatisations actives", "Recent activity": "Activité récente", "Performance": "Performances", "View all": "Tout afficher", "Welcome back,": "Bon retour,",
  "Continue": "Continuer", "Back": "Retour", "Save": "Enregistrer", "Saving...": "Enregistrement...", "Save as draft": "Enregistrer comme brouillon", "Cancel": "Annuler", "Close": "Fermer", "Refresh": "Actualiser", "Preview": "Aperçu", "Optional": "Facultatif", "Monthly": "Mensuel", "Annual": "Annuel", "Current plan": "Forfait actuel", "Manage billing": "Gérer la facturation", "Upgrade": "Mettre à niveau", "Upgrade to Pro": "Passer à Pro",
  "Connect Instagram": "Connecter Instagram", "Reconnect Instagram": "Reconnecter Instagram", "Instagram connected": "Instagram connecté", "Instagram not connected": "Instagram non connecté", "Remove connection": "Supprimer la connexion", "Manage connection": "Gérer la connexion", "Connection health": "État de la connexion", "Permission readiness": "État des autorisations", "Your Instagram": "Votre Instagram", "Instagram performance": "Performances Instagram",
  "Choose a post or Reel": "Choisissez une publication ou un Reel", "Choose a specific post or Reel": "Choisissez une publication ou un Reel précis", "Any post": "Toute publication", "Specific keyword": "Mot-clé précis", "What comment starts this automation?": "Quel commentaire déclenche cette automatisation ?", "What should AP3K do?": "Que doit faire AP3K ?", "Reply to comment": "Répondre au commentaire", "Send a DM": "Envoyer un DM", "Opening DM": "DM d’ouverture", "DM with links": "DM avec liens", "Follow request DM": "DM de demande d’abonnement", "Optional follow request": "Demande d’abonnement facultative", "Review & Activate": "Vérifier et activer", "Active automation": "Automatisation active", "Go live": "Activer",
  "Automation name": "Nom de l’automatisation", "Add link": "Ajouter un lien", "Button label": "Libellé du bouton", "Destination URL": "URL de destination", "Opening message": "Message d’ouverture", "DM message text": "Texte du DM", "Add words that trigger automation": "Ajoutez les mots qui déclenchent l’automatisation", "No keywords": "Aucun mot-clé", "Search posts": "Rechercher des publications", "No Posts Found": "Aucune publication trouvée", "Show all posts": "Afficher toutes les publications", "Close preview": "Fermer l’aperçu", "Edit automation": "Modifier l’automatisation", "Back to automations": "Retour aux automatisations",
  "All chats": "Toutes les discussions", "Unread": "Non lus", "Recent": "Récents", "Search conversations": "Rechercher des conversations", "Open chat": "Ouvrir la discussion", "Message…": "Écrivez un message…", "Add emoji": "Ajouter un emoji", "Send": "Envoyer", "Updates automatically": "Actualisation automatique", "No messages in this conversation yet.": "Aucun message dans cette conversation.", "Search contacts": "Rechercher des contacts", "Search by Instagram username": "Rechercher par nom Instagram", "Instagram contact": "Contact Instagram", "Source": "Source",
  "AP3K AI": "IA AP3K", "AI Comments": "Commentaires IA", "Knowledge base": "Base de connaissances", "Add knowledge": "Ajouter une information", "Saved knowledge": "Connaissances enregistrées", "Behavior": "Comportement", "Comment protection": "Protection des commentaires", "Ask a customer-style question": "Posez une question comme un client", "Send test": "Envoyer le test", "Thinking…": "Réflexion…", "Save changes": "Enregistrer les modifications", "Upgrade to enable AI comments, AI DM replies, knowledge, and the playground.": "Passez à un forfait supérieur pour activer les commentaires et DM par IA, les connaissances et le playground.",
  "Preferences": "Préférences", "Appearance": "Apparence", "Account & authentication": "Compte et authentification", "Email notifications": "Notifications par e-mail", "Save email preferences": "Enregistrer les préférences e-mail", "Delete account permanently": "Supprimer définitivement le compte", "This action cannot be undone.": "Cette action est irréversible.", "Keep my account": "Conserver mon compte", "Cookie preferences": "Préférences de cookies", "Accept analytics": "Accepter les statistiques", "Your privacy, your choice": "Votre vie privée, votre choix", "Get help": "Obtenir de l’aide", "Email support": "Contacter le support", "How can we help?": "Comment pouvons-nous vous aider ?", "Search AP3K help…": "Rechercher dans l’aide AP3K…", "Ask a question…": "Posez une question…", "Try again": "Réessayer",
};

const es: ProductCatalog = Object.fromEntries(Object.keys(fr).map((key) => [key, key]));
const de: ProductCatalog = Object.fromEntries(Object.keys(fr).map((key) => [key, key]));
const pt: ProductCatalog = Object.fromEntries(Object.keys(fr).map((key) => [key, key]));

Object.assign(es, {
  Automations: "Automatizaciones", Inbox: "Bandeja de entrada", Contacts: "Contactos", "AI Replies": "Respuestas con IA", Account: "Cuenta", Billing: "Facturación", Settings: "Configuración", Help: "Ayuda", Referrals: "Referidos", Integrations: "Integraciones", "Create automation": "Crear automatización", "+ New automation": "+ Nueva automatización", Continue: "Continuar", Back: "Atrás", Save: "Guardar", Cancel: "Cancelar", Close: "Cerrar", Refresh: "Actualizar", Preview: "Vista previa", Optional: "Opcional", Monthly: "Mensual", Annual: "Anual", "Connect Instagram": "Conectar Instagram", "Reconnect Instagram": "Volver a conectar Instagram", "Send a DM": "Enviar un DM", "Reply to comment": "Responder al comentario", "Automation name": "Nombre de la automatización", "Add link": "Añadir enlace", "Button label": "Texto del botón", "Destination URL": "URL de destino", "All chats": "Todos los chats", Unread: "No leídos", Recent: "Recientes", Send: "Enviar", "Search conversations": "Buscar conversaciones", "Search contacts": "Buscar contactos", "Knowledge base": "Base de conocimientos", Behavior: "Comportamiento", "Save changes": "Guardar cambios", Preferences: "Preferencias", Appearance: "Apariencia", "Email notifications": "Notificaciones por correo", "This action cannot be undone.": "Esta acción no se puede deshacer.", "Try again": "Intentar de nuevo",
});
Object.assign(es, {
  "+ Create Automation": "+ Crear automatización", "Create your first automation": "Crea tu primera automatización", "No automations yet": "Aún no hay automatizaciones", "Active automations": "Automatizaciones activas", "Recent activity": "Actividad reciente", Performance: "Rendimiento", "View all": "Ver todo", "Welcome back,": "Te damos la bienvenida de nuevo,", "Saving...": "Guardando...", "Save as draft": "Guardar como borrador", "Current plan": "Plan actual", "Manage billing": "Gestionar facturación", Upgrade: "Mejorar plan", "Upgrade to Pro": "Mejorar a Pro",
  "Instagram connected": "Instagram conectado", "Instagram not connected": "Instagram no conectado", "Remove connection": "Eliminar conexión", "Manage connection": "Gestionar conexión", "Connection health": "Estado de la conexión", "Permission readiness": "Estado de los permisos", "Your Instagram": "Tu Instagram", "Instagram performance": "Rendimiento de Instagram", "Choose a post or Reel": "Elige una publicación o Reel", "Choose a specific post or Reel": "Elige una publicación o Reel específico", "Any post": "Cualquier publicación", "Specific keyword": "Palabra clave específica", "What comment starts this automation?": "¿Qué comentario inicia esta automatización?", "What should AP3K do?": "¿Qué debe hacer AP3K?", "Opening DM": "DM de apertura", "DM with links": "DM con enlaces", "Follow request DM": "DM para solicitar seguimiento", "Optional follow request": "Solicitud de seguimiento opcional", "Review & Activate": "Revisar y activar", "Active automation": "Automatización activa", "Go live": "Activar",
  "Opening message": "Mensaje de apertura", "DM message text": "Texto del DM", "Add words that trigger automation": "Añade palabras que activen la automatización", "No keywords": "Sin palabras clave", "Search posts": "Buscar publicaciones", "No Posts Found": "No se encontraron publicaciones", "Show all posts": "Mostrar todas las publicaciones", "Close preview": "Cerrar vista previa", "Edit automation": "Editar automatización", "Back to automations": "Volver a automatizaciones", "Open chat": "Abrir chat", "Message…": "Escribe un mensaje…", "Add emoji": "Añadir emoji", "Updates automatically": "Se actualiza automáticamente", "No messages in this conversation yet.": "Aún no hay mensajes en esta conversación.", "Search by Instagram username": "Buscar por usuario de Instagram", "Instagram contact": "Contacto de Instagram", Source: "Origen",
  "AP3K AI": "IA de AP3K", "AI Comments": "Comentarios con IA", "Add knowledge": "Añadir información", "Saved knowledge": "Conocimiento guardado", "Comment protection": "Protección de comentarios", "Ask a customer-style question": "Haz una pregunta como cliente", "Send test": "Enviar prueba", "Thinking…": "Pensando…", "Upgrade to enable AI comments, AI DM replies, knowledge, and the playground.": "Mejora tu plan para activar comentarios y DM con IA, conocimiento y el entorno de pruebas.", "Account & authentication": "Cuenta y autenticación", "Save email preferences": "Guardar preferencias de correo", "Delete account permanently": "Eliminar la cuenta permanentemente", "Keep my account": "Conservar mi cuenta", "Cookie preferences": "Preferencias de cookies", "Accept analytics": "Aceptar analíticas", "Your privacy, your choice": "Tu privacidad, tu elección", "Get help": "Obtener ayuda", "Email support": "Contactar con soporte", "How can we help?": "¿Cómo podemos ayudarte?", "Search AP3K help…": "Buscar en la ayuda de AP3K…", "Ask a question…": "Haz una pregunta…",
});
Object.assign(de, {
  Automations: "Automatisierungen", Inbox: "Posteingang", Contacts: "Kontakte", "AI Replies": "KI-Antworten", Account: "Konto", Billing: "Abrechnung", Settings: "Einstellungen", Help: "Hilfe", Referrals: "Empfehlungen", Integrations: "Integrationen", "Create automation": "Automatisierung erstellen", "+ New automation": "+ Neue Automatisierung", Continue: "Weiter", Back: "Zurück", Save: "Speichern", Cancel: "Abbrechen", Close: "Schließen", Refresh: "Aktualisieren", Preview: "Vorschau", Optional: "Optional", Monthly: "Monatlich", Annual: "Jährlich", "Connect Instagram": "Instagram verbinden", "Reconnect Instagram": "Instagram erneut verbinden", "Send a DM": "DM senden", "Reply to comment": "Auf Kommentar antworten", "Automation name": "Name der Automatisierung", "Add link": "Link hinzufügen", "Button label": "Button-Text", "Destination URL": "Ziel-URL", "All chats": "Alle Chats", Unread: "Ungelesen", Recent: "Neueste", Send: "Senden", "Search conversations": "Unterhaltungen suchen", "Search contacts": "Kontakte suchen", "Knowledge base": "Wissensdatenbank", Behavior: "Verhalten", "Save changes": "Änderungen speichern", Preferences: "Einstellungen", Appearance: "Darstellung", "Email notifications": "E-Mail-Benachrichtigungen", "This action cannot be undone.": "Diese Aktion kann nicht rückgängig gemacht werden.", "Try again": "Erneut versuchen",
});
Object.assign(de, {
  "+ Create Automation": "+ Automatisierung erstellen", "Create your first automation": "Erstelle deine erste Automatisierung", "No automations yet": "Noch keine Automatisierungen", "Active automations": "Aktive Automatisierungen", "Recent activity": "Letzte Aktivitäten", Performance: "Leistung", "View all": "Alle anzeigen", "Welcome back,": "Willkommen zurück,", "Saving...": "Wird gespeichert...", "Save as draft": "Als Entwurf speichern", "Current plan": "Aktueller Tarif", "Manage billing": "Abrechnung verwalten", Upgrade: "Upgrade", "Upgrade to Pro": "Auf Pro upgraden",
  "Instagram connected": "Instagram verbunden", "Instagram not connected": "Instagram nicht verbunden", "Remove connection": "Verbindung entfernen", "Manage connection": "Verbindung verwalten", "Connection health": "Verbindungsstatus", "Permission readiness": "Berechtigungsstatus", "Your Instagram": "Dein Instagram", "Instagram performance": "Instagram-Leistung", "Choose a post or Reel": "Beitrag oder Reel auswählen", "Choose a specific post or Reel": "Bestimmten Beitrag oder Reel auswählen", "Any post": "Jeder Beitrag", "Specific keyword": "Bestimmtes Keyword", "What comment starts this automation?": "Welcher Kommentar startet diese Automatisierung?", "What should AP3K do?": "Was soll AP3K tun?", "Opening DM": "Eröffnungs-DM", "DM with links": "DM mit Links", "Follow request DM": "DM mit Follow-Aufforderung", "Optional follow request": "Optionale Follow-Aufforderung", "Review & Activate": "Prüfen und aktivieren", "Active automation": "Aktive Automatisierung", "Go live": "Aktivieren",
  "Opening message": "Eröffnungsnachricht", "DM message text": "DM-Nachrichtentext", "Add words that trigger automation": "Wörter hinzufügen, die die Automatisierung auslösen", "No keywords": "Keine Keywords", "Search posts": "Beiträge suchen", "No Posts Found": "Keine Beiträge gefunden", "Show all posts": "Alle Beiträge anzeigen", "Close preview": "Vorschau schließen", "Edit automation": "Automatisierung bearbeiten", "Back to automations": "Zurück zu Automatisierungen", "Open chat": "Chat öffnen", "Message…": "Nachricht schreiben…", "Add emoji": "Emoji hinzufügen", "Updates automatically": "Wird automatisch aktualisiert", "No messages in this conversation yet.": "Noch keine Nachrichten in dieser Unterhaltung.", "Search by Instagram username": "Nach Instagram-Benutzername suchen", "Instagram contact": "Instagram-Kontakt", Source: "Quelle",
  "AP3K AI": "AP3K KI", "AI Comments": "KI-Kommentare", "Add knowledge": "Wissen hinzufügen", "Saved knowledge": "Gespeichertes Wissen", "Comment protection": "Kommentarschutz", "Ask a customer-style question": "Stelle eine Frage wie ein Kunde", "Send test": "Test senden", "Thinking…": "Denke nach…", "Upgrade to enable AI comments, AI DM replies, knowledge, and the playground.": "Führe ein Upgrade durch, um KI-Kommentare, KI-DMs, Wissen und den Testbereich zu aktivieren.", "Account & authentication": "Konto und Anmeldung", "Save email preferences": "E-Mail-Einstellungen speichern", "Delete account permanently": "Konto dauerhaft löschen", "Keep my account": "Mein Konto behalten", "Cookie preferences": "Cookie-Einstellungen", "Accept analytics": "Analysen akzeptieren", "Your privacy, your choice": "Deine Privatsphäre, deine Wahl", "Get help": "Hilfe erhalten", "Email support": "Support kontaktieren", "How can we help?": "Wie können wir helfen?", "Search AP3K help…": "AP3K-Hilfe durchsuchen…", "Ask a question…": "Frage stellen…",
});
Object.assign(pt, {
  Automations: "Automações", Inbox: "Caixa de entrada", Contacts: "Contactos", "AI Replies": "Respostas de IA", Account: "Conta", Billing: "Faturação", Settings: "Definições", Help: "Ajuda", Referrals: "Referências", Integrations: "Integrações", "Create automation": "Criar automação", "+ New automation": "+ Nova automação", Continue: "Continuar", Back: "Voltar", Save: "Guardar", Cancel: "Cancelar", Close: "Fechar", Refresh: "Atualizar", Preview: "Pré-visualização", Optional: "Opcional", Monthly: "Mensal", Annual: "Anual", "Connect Instagram": "Ligar Instagram", "Reconnect Instagram": "Voltar a ligar o Instagram", "Send a DM": "Enviar DM", "Reply to comment": "Responder ao comentário", "Automation name": "Nome da automação", "Add link": "Adicionar ligação", "Button label": "Texto do botão", "Destination URL": "URL de destino", "All chats": "Todas as conversas", Unread: "Não lidas", Recent: "Recentes", Send: "Enviar", "Search conversations": "Pesquisar conversas", "Search contacts": "Pesquisar contactos", "Knowledge base": "Base de conhecimento", Behavior: "Comportamento", "Save changes": "Guardar alterações", Preferences: "Preferências", Appearance: "Aspeto", "Email notifications": "Notificações por e-mail", "This action cannot be undone.": "Esta ação não pode ser anulada.", "Try again": "Tentar novamente",
});
Object.assign(pt, {
  "+ Create Automation": "+ Criar automação", "Create your first automation": "Crie a sua primeira automação", "No automations yet": "Ainda não há automações", "Active automations": "Automações ativas", "Recent activity": "Atividade recente", Performance: "Desempenho", "View all": "Ver tudo", "Welcome back,": "Bem-vindo de volta,", "Saving...": "A guardar...", "Save as draft": "Guardar como rascunho", "Current plan": "Plano atual", "Manage billing": "Gerir faturação", Upgrade: "Atualizar plano", "Upgrade to Pro": "Atualizar para Pro",
  "Instagram connected": "Instagram ligado", "Instagram not connected": "Instagram não ligado", "Remove connection": "Remover ligação", "Manage connection": "Gerir ligação", "Connection health": "Estado da ligação", "Permission readiness": "Estado das permissões", "Your Instagram": "O seu Instagram", "Instagram performance": "Desempenho do Instagram", "Choose a post or Reel": "Escolha uma publicação ou Reel", "Choose a specific post or Reel": "Escolha uma publicação ou Reel específico", "Any post": "Qualquer publicação", "Specific keyword": "Palavra-chave específica", "What comment starts this automation?": "Que comentário inicia esta automação?", "What should AP3K do?": "O que deve o AP3K fazer?", "Opening DM": "DM inicial", "DM with links": "DM com ligações", "Follow request DM": "DM a pedir para seguir", "Optional follow request": "Pedido para seguir opcional", "Review & Activate": "Rever e ativar", "Active automation": "Automação ativa", "Go live": "Ativar",
  "Opening message": "Mensagem inicial", "DM message text": "Texto da DM", "Add words that trigger automation": "Adicione palavras que acionam a automação", "No keywords": "Sem palavras-chave", "Search posts": "Pesquisar publicações", "No Posts Found": "Nenhuma publicação encontrada", "Show all posts": "Mostrar todas as publicações", "Close preview": "Fechar pré-visualização", "Edit automation": "Editar automação", "Back to automations": "Voltar às automações", "Open chat": "Abrir conversa", "Message…": "Escreva uma mensagem…", "Add emoji": "Adicionar emoji", "Updates automatically": "Atualiza automaticamente", "No messages in this conversation yet.": "Ainda não há mensagens nesta conversa.", "Search by Instagram username": "Pesquisar por nome de utilizador do Instagram", "Instagram contact": "Contacto do Instagram", Source: "Origem",
  "AP3K AI": "IA do AP3K", "AI Comments": "Comentários de IA", "Add knowledge": "Adicionar informação", "Saved knowledge": "Conhecimento guardado", "Comment protection": "Proteção de comentários", "Ask a customer-style question": "Faça uma pergunta como cliente", "Send test": "Enviar teste", "Thinking…": "A pensar…", "Upgrade to enable AI comments, AI DM replies, knowledge, and the playground.": "Atualize o plano para ativar comentários e DMs com IA, conhecimento e a área de testes.", "Account & authentication": "Conta e autenticação", "Save email preferences": "Guardar preferências de e-mail", "Delete account permanently": "Eliminar conta permanentemente", "Keep my account": "Manter a minha conta", "Cookie preferences": "Preferências de cookies", "Accept analytics": "Aceitar análise", "Your privacy, your choice": "A sua privacidade, a sua escolha", "Get help": "Obter ajuda", "Email support": "Contactar suporte", "How can we help?": "Como podemos ajudar?", "Search AP3K help…": "Pesquisar na ajuda do AP3K…", "Ask a question…": "Faça uma pergunta…",
});

export const PRODUCT_PHRASE_TRANSLATIONS: Record<Locale, ProductCatalog> = { en, ar, fr, es, de, pt };
