import type { Locale } from "./config";

type ReferralCopy = {
  kicker: string; title: string; description: string; foundingTitle: string;
  founderSecured: string; spotPending: string; programFull: string;
  howEarn: string; stepsTitle: string; perFriend: string;
  steps: Array<{ title: string; text: string }>;
  freeCredit: string; summary: [string, string, string, string];
  activity: string; friends: string; pending: string; joined: string;
  noFriends: string; noFriendsDescription: string; rulesTitle: string; rulesBody: string;
  partner: string; spotsOpen: string; spotsFilled: string; step: string;
  statuses: { qualified: string; reversed: string; connected: string; waitlisted: string; invited: string };
};

export const REFERRAL_COPY: Record<Locale, ReferralCopy> = {
  en: {
    kicker: "Refer & earn", title: "Give free actions. Get $9 credit.", description: "Invite a friend to AP3K. When they connect Instagram and pay for a plan, you earn $9 toward your next invoice.", foundingTitle: "Founding 10 rewards",
    founderSecured: "Your Founding Partner spot is secured. Every qualifying referral earns another $9 credit.", spotPending: "Your spot is secured when your first referral qualifies. Spots are assigned in payment order.", programFull: "All Founding Partner spots are currently claimed. You can still share your link and track referrals.",
    howEarn: "How you earn", stepsTitle: "Three simple steps", perFriend: "$9 per qualified friend", steps: [{ title: "They join", text: "They create a new account using your link." }, { title: "They connect", text: "They connect a Business or Creator Instagram." }, { title: "They subscribe", text: "Their first Pro or Business payment earns your credit." }],
    freeCredit: "Your friend gets 500 automated actions each month on Free. Your credit is applied automatically to a future AP3K invoice.", summary: ["Signed up", "Instagram ready", "Rewards earned", "Total credit"],
    activity: "Referral activity", friends: "Your friends", pending: "pending", joined: "Joined", noFriends: "No friends yet", noFriendsDescription: "Copy your link above and send your first invitation.", rulesTitle: "Eligibility and rules", rulesBody: "A referral qualifies after a new user joins through your link, connects Instagram, and completes a successful Pro or Business payment of at least $9 USD. One reward per referred account. Self-referrals, duplicate accounts, refunded payments, disputes, and fraud do not qualify. Credits are not cash or transferable. Founding spots are assigned in qualifying-payment order.",
    partner: "Partner", spotsOpen: "spots open", spotsFilled: "Spots filled", step: "Step", statuses: { qualified: "$9 earned", reversed: "Reward reversed", connected: "Needs a plan", waitlisted: "Program full", invited: "Needs Instagram" },
  },
  fr: {
    kicker: "Parrainage", title: "Offrez des actions gratuites. Recevez 9 $ de crédit.", description: "Invitez un ami sur AP3K. Lorsqu’il connecte Instagram et paie une offre, vous recevez 9 $ sur votre prochaine facture.", foundingTitle: "Récompenses des 10 fondateurs",
    founderSecured: "Votre place de partenaire fondateur est confirmée. Chaque parrainage éligible vous rapporte 9 $ de crédit supplémentaires.", spotPending: "Votre place est confirmée lorsque votre premier parrainage devient éligible. Les places suivent l’ordre des paiements.", programFull: "Toutes les places de partenaire fondateur sont prises. Vous pouvez toujours partager votre lien et suivre vos parrainages.",
    howEarn: "Comment gagner", stepsTitle: "Trois étapes simples", perFriend: "9 $ par ami éligible", steps: [{ title: "Il s’inscrit", text: "Il crée un compte avec votre lien." }, { title: "Il se connecte", text: "Il connecte un compte Instagram Business ou Creator." }, { title: "Il s’abonne", text: "Son premier paiement Pro ou Business génère votre crédit." }],
    freeCredit: "Votre ami reçoit 500 actions automatisées par mois avec l’offre gratuite. Votre crédit est appliqué automatiquement à une future facture AP3K.", summary: ["Inscriptions", "Instagram prêt", "Récompenses", "Crédit total"],
    activity: "Activité de parrainage", friends: "Vos amis", pending: "en attente", joined: "Inscrit le", noFriends: "Aucun ami pour le moment", noFriendsDescription: "Copiez votre lien ci-dessus et envoyez votre première invitation.", rulesTitle: "Éligibilité et règles", rulesBody: "Un parrainage devient éligible lorsqu’un nouvel utilisateur s’inscrit avec votre lien, connecte Instagram et règle avec succès au moins 9 $ US pour une offre Pro ou Business. Une récompense par compte parrainé. Les auto-parrainages, doublons, paiements remboursés, litiges et fraudes sont exclus. Les crédits ne sont ni monétaires ni transférables. Les places fondatrices suivent l’ordre des paiements éligibles.",
    partner: "Partenaire", spotsOpen: "places disponibles", spotsFilled: "Places complètes", step: "Étape", statuses: { qualified: "9 $ gagnés", reversed: "Récompense annulée", connected: "Offre requise", waitlisted: "Programme complet", invited: "Instagram requis" },
  },
  es: {
    kicker: "Recomienda y gana", title: "Regala acciones gratis. Consigue $9 de crédito.", description: "Invita a un amigo a AP3K. Cuando conecte Instagram y pague un plan, recibirás $9 para tu próxima factura.", foundingTitle: "Recompensas para los 10 fundadores",
    founderSecured: "Tu plaza de socio fundador está asegurada. Cada recomendación válida añade otros $9 de crédito.", spotPending: "Tu plaza se asegura cuando se valida tu primera recomendación. Se asignan por orden de pago.", programFull: "Todas las plazas de socio fundador están ocupadas. Aún puedes compartir tu enlace y seguir tus recomendaciones.",
    howEarn: "Cómo ganas", stepsTitle: "Tres pasos sencillos", perFriend: "$9 por amigo válido", steps: [{ title: "Se registra", text: "Crea una cuenta nueva con tu enlace." }, { title: "Se conecta", text: "Conecta una cuenta Business o Creator de Instagram." }, { title: "Se suscribe", text: "Su primer pago Pro o Business genera tu crédito." }],
    freeCredit: "Tu amigo recibe 500 acciones automatizadas al mes con el plan Gratis. Tu crédito se aplica automáticamente a una futura factura de AP3K.", summary: ["Registrados", "Instagram listo", "Recompensas", "Crédito total"],
    activity: "Actividad de recomendaciones", friends: "Tus amigos", pending: "pendiente", joined: "Se registró", noFriends: "Aún no hay amigos", noFriendsDescription: "Copia tu enlace y envía tu primera invitación.", rulesTitle: "Requisitos y reglas", rulesBody: "Una recomendación es válida cuando un usuario nuevo se registra con tu enlace, conecta Instagram y completa un pago Pro o Business de al menos $9 USD. Una recompensa por cuenta recomendada. No se admiten autorreferencias, cuentas duplicadas, pagos reembolsados, disputas ni fraude. Los créditos no son dinero ni se pueden transferir. Las plazas fundadoras se asignan por orden de pago válido.",
    partner: "Socio", spotsOpen: "plazas disponibles", spotsFilled: "Plazas completas", step: "Paso", statuses: { qualified: "$9 ganados", reversed: "Recompensa anulada", connected: "Necesita un plan", waitlisted: "Programa completo", invited: "Necesita Instagram" },
  },
  de: {
    kicker: "Empfehlen & verdienen", title: "Verschenke kostenlose Aktionen. Erhalte 9 $ Guthaben.", description: "Lade Freunde zu AP3K ein. Wenn sie Instagram verbinden und einen Tarif bezahlen, erhältst du 9 $ für deine nächste Rechnung.", foundingTitle: "Prämien für die ersten 10 Partner",
    founderSecured: "Dein Platz als Gründungspartner ist gesichert. Jede gültige Empfehlung bringt weitere 9 $ Guthaben.", spotPending: "Dein Platz wird mit der ersten gültigen Empfehlung gesichert. Die Vergabe erfolgt nach Zahlungseingang.", programFull: "Alle Plätze für Gründungspartner sind belegt. Du kannst deinen Link weiterhin teilen und Empfehlungen verfolgen.",
    howEarn: "So verdienst du", stepsTitle: "Drei einfache Schritte", perFriend: "9 $ pro gültigem Freund", steps: [{ title: "Registrierung", text: "Die Person erstellt über deinen Link ein neues Konto." }, { title: "Instagram verbinden", text: "Sie verbindet ein Instagram-Business- oder Creator-Konto." }, { title: "Abo abschließen", text: "Die erste Pro- oder Business-Zahlung erzeugt dein Guthaben." }],
    freeCredit: "Dein Freund erhält im kostenlosen Tarif monatlich 500 automatisierte Aktionen. Dein Guthaben wird automatisch auf eine zukünftige AP3K-Rechnung angerechnet.", summary: ["Registriert", "Instagram bereit", "Prämien", "Gesamtguthaben"],
    activity: "Empfehlungsaktivität", friends: "Deine Freunde", pending: "ausstehend", joined: "Beigetreten", noFriends: "Noch keine Freunde", noFriendsDescription: "Kopiere deinen Link und sende deine erste Einladung.", rulesTitle: "Teilnahmebedingungen", rulesBody: "Eine Empfehlung gilt, wenn sich ein neuer Nutzer über deinen Link registriert, Instagram verbindet und eine erfolgreiche Pro- oder Business-Zahlung von mindestens 9 USD abschließt. Eine Prämie pro empfohlenem Konto. Eigenempfehlungen, doppelte Konten, Erstattungen, Zahlungsstreitigkeiten und Betrug sind ausgeschlossen. Guthaben ist weder Bargeld noch übertragbar. Gründungsplätze werden nach Eingang gültiger Zahlungen vergeben.",
    partner: "Partner", spotsOpen: "Plätze frei", spotsFilled: "Alle Plätze belegt", step: "Schritt", statuses: { qualified: "9 $ verdient", reversed: "Prämie storniert", connected: "Tarif erforderlich", waitlisted: "Programm voll", invited: "Instagram erforderlich" },
  },
  pt: {
    kicker: "Recomendar e ganhar", title: "Ofereça ações grátis. Receba 9 $ de crédito.", description: "Convide um amigo para o AP3K. Quando ligar o Instagram e pagar um plano, recebe 9 $ para a próxima fatura.", foundingTitle: "Recompensas dos 10 fundadores",
    founderSecured: "O seu lugar de parceiro fundador está garantido. Cada recomendação elegível acrescenta mais 9 $ de crédito.", spotPending: "O lugar fica garantido quando a primeira recomendação se qualifica. As vagas seguem a ordem de pagamento.", programFull: "Todas as vagas de parceiro fundador estão ocupadas. Ainda pode partilhar o link e acompanhar recomendações.",
    howEarn: "Como ganhar", stepsTitle: "Três passos simples", perFriend: "9 $ por amigo elegível", steps: [{ title: "Adere", text: "Cria uma conta nova através do seu link." }, { title: "Liga o Instagram", text: "Liga uma conta Business ou Creator do Instagram." }, { title: "Subscreve", text: "O primeiro pagamento Pro ou Business gera o seu crédito." }],
    freeCredit: "O seu amigo recebe 500 ações automatizadas por mês no plano Grátis. O crédito é aplicado automaticamente a uma futura fatura do AP3K.", summary: ["Registados", "Instagram pronto", "Recompensas", "Crédito total"],
    activity: "Atividade de recomendações", friends: "Os seus amigos", pending: "pendente", joined: "Aderiu", noFriends: "Ainda não há amigos", noFriendsDescription: "Copie o link acima e envie o primeiro convite.", rulesTitle: "Elegibilidade e regras", rulesBody: "Uma recomendação qualifica-se quando um novo utilizador adere pelo seu link, liga o Instagram e conclui um pagamento Pro ou Business de pelo menos 9 USD. Uma recompensa por conta recomendada. Auto-recomendações, contas duplicadas, pagamentos reembolsados, litígios e fraude não são elegíveis. Os créditos não são dinheiro nem transferíveis. As vagas de fundador seguem a ordem dos pagamentos elegíveis.",
    partner: "Parceiro", spotsOpen: "vagas disponíveis", spotsFilled: "Vagas preenchidas", step: "Passo", statuses: { qualified: "9 $ ganhos", reversed: "Recompensa anulada", connected: "Precisa de um plano", waitlisted: "Programa completo", invited: "Precisa do Instagram" },
  },
};
