"use client";
import { useState } from "react";
import { Clock3, X } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { useUi } from "@/components/i18n/use-ui";
import { EditorSelect } from "./editor-select";
import { editorStyles as s } from "./editor-layout";
export default function DelayControl({seconds,onChange,label="next step"}:{seconds:number;onChange:(n:number)=>void;label?:string}) {
 const tr=useUi();const [open,setOpen]=useState(false);const [amount,setAmount]=useState(10);const [unit,setUnit]=useState("1");
 const displayAmount=seconds%3600===0?seconds/3600:seconds%60===0?seconds/60:seconds;
 const displayUnit=seconds%3600===0?(displayAmount===1?"hour":"hours"):seconds%60===0?(displayAmount===1?"minute":"minutes"):(displayAmount===1?"second":"seconds");
 const displayLabel=seconds ? `${displayAmount} ${tr(displayUnit)}` : tr("Add delay");
 return <div className={s.delayRow}><span className={s.rowIcon}><Clock3/></span><Popover open={open} onOpenChange={v=>{setOpen(v);if(v){const u=seconds && seconds%3600===0?3600:seconds && seconds%60===0?60:1;setUnit(String(u));setAmount(seconds?seconds/u:10);}}}><PopoverTrigger asChild><button type="button" aria-label={`${tr("Delay before")} ${tr(label)}`} className={s.delayPill}>{displayLabel}</button></PopoverTrigger><PopoverContent align="start" className="w-[min(380px,calc(100vw-32px))] rounded-2xl bg-white p-5 text-slate-950 shadow-xl dark:bg-[#141521] dark:text-slate-50"><div className="mb-5 flex items-center justify-between"><strong>{tr("Wait before next step")}</strong><button aria-label={tr("Close")} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="mb-4 grid grid-cols-2 gap-3"><input aria-label={tr("Delay amount")} type="number" min="1" max={82800/Number(unit)} value={amount} onChange={e=>setAmount(Number(e.target.value))} className="min-w-0 rounded-xl border bg-transparent p-3 dark:border-white/15"/><EditorSelect label="Delay unit" value={unit} onChange={setUnit} options={[{value:"1",label:"seconds"},{value:"60",label:"minutes"},{value:"3600",label:"hours"}]}/></div><p className="mb-5 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-600 dark:bg-white/5 dark:text-slate-300">{tr("A short pause makes replies feel human instead of instant.")}<span className="mt-1 block text-xs">{tr("Delivery may be later depending on the scheduler. Maximum 23 hours.")}</span></p><div className="grid grid-cols-2 gap-3"><button className="rounded-xl border p-3 dark:border-white/15" onClick={()=>setOpen(false)}>{tr("Cancel")}</button><button className="rounded-xl bg-slate-950 p-3 font-semibold text-white disabled:opacity-50 dark:bg-white dark:text-slate-950" disabled={!Number.isFinite(amount)||amount<1||amount*Number(unit)>82800} onClick={()=>{onChange(Math.floor(amount*Number(unit)));setOpen(false);}}>{tr("Add delay")}</button></div></PopoverContent></Popover>{seconds>0&&<button type="button" aria-label={`${tr("Remove delay")} ${tr(label)}`} onClick={()=>onChange(0)}><X size={15}/></button>}</div>;
}
