"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, Sparkles, Zap, Building2 } from "lucide-react";
import { PLAN_CARDS, checkoutHref, type BillingInterval, type PaidPlan } from "@/lib/billing-plans";
import { useUi } from "@/components/i18n/use-ui";
import ThemeToggle from "@/components/global/theme-toggle";
export default function ChoosePlan({slug,paid}:{slug:string;paid:boolean}) {
 const tr=useUi();const [interval,setInterval]=useState<BillingInterval>("month");
 const destination=`/dashboard/${slug}/automation/new`;
 return <section className="w-full" aria-labelledby="choose-plan-title">
 <header className="mb-10 flex items-center justify-between"><Link href="/" className="text-xl font-black tracking-tight">AP3K<span className="text-violet-500">.</span></Link><ThemeToggle compact/></header>
 <div className="mb-9 text-center"><h1 id="choose-plan-title" className="text-3xl font-semibold tracking-tight sm:text-4xl">{tr("Choose your plan")}</h1><p className="mt-3 text-sm text-slate-500 dark:text-slate-400">{tr("Start free · Upgrade anytime · Cancel whenever")}</p><div role="group" aria-label={tr("Billing interval")} className="mx-auto mt-7 flex w-fit gap-1 rounded-full bg-slate-100 p-1.5 dark:bg-white/10">{(["year","month"] as const).map(v=><button type="button" key={v} aria-pressed={interval===v} onClick={()=>setInterval(v)} className={`min-w-28 rounded-full px-5 py-2.5 text-sm font-semibold ${interval===v?"bg-white text-slate-950 shadow-sm dark:bg-slate-700 dark:text-white":"text-slate-500 dark:text-slate-400"}`}>{tr(v==="year"?"Yearly":"Monthly")}</button>)}</div><p className="mt-3 text-xs text-slate-500 dark:text-slate-400">{tr("Save up to 27% with annual billing")}</p></div>
 <div className="grid gap-5 md:grid-cols-3">{PLAN_CARDS.map((plan,i)=>{const featured=plan.featured;const free=plan.id==="FREE";const price=interval==="year"?(plan.annualPrice??0)/12:plan.monthlyPrice??0;const Icon=[Zap,Sparkles,Building2][i];return <article key={plan.id} className={`flex flex-col rounded-3xl p-3 ${featured?"bg-[#17181c] text-white":"bg-[#f4f4f6] text-slate-950 dark:bg-[#171a26] dark:text-slate-50"}`}>
 <div className={`rounded-2xl p-5 ${featured?"bg-[#27282d]":"bg-white dark:bg-[#222636]"}`}><div className="mb-5 flex items-center justify-between gap-2"><span className="flex items-center gap-2 font-semibold"><Icon size={19}/>{plan.name}</span>{i>0&&<span className={`rounded-full px-2.5 py-1 text-[9px] font-bold tracking-wider ${featured?"bg-blue-600 text-white":"bg-slate-900 text-white dark:bg-white/15"}`}>{tr(featured?"MOST POPULAR":"ADVANCED")}</span>}</div><div className="flex items-baseline gap-1"><span className="text-5xl font-semibold tracking-tight">${Number.isInteger(price)?price:price.toFixed(2)}</span><span className={`text-xs ${featured?"text-slate-300":"text-slate-500 dark:text-slate-400"}`}>/ {tr("month")}</span></div><p className={`mt-3 min-h-10 text-xs leading-5 ${featured?"text-slate-300":"text-slate-500 dark:text-slate-400"}`}>{free?tr("Free forever. No credit card required."):interval==="year"?`$${plan.annualPrice} ${tr("billed yearly")}`:tr("Billed monthly")}</p><Link href={paid?`/dashboard/${slug}/billing`:free?destination:checkoutHref(plan.id as PaidPlan,interval)} className={`mt-6 flex min-h-12 items-center justify-center gap-2 rounded-xl text-sm font-semibold ${featured?"bg-blue-600 text-white hover:bg-blue-500":free?"border border-slate-200 bg-white text-slate-950 dark:border-white/15 dark:bg-white/5 dark:text-white":"bg-slate-950 text-white dark:bg-white dark:text-slate-950"}`}>{tr(paid?"Manage plan":free?"Start for free":`Upgrade to ${plan.name}`)}<ArrowRight size={15}/></Link></div>
 <div className="flex-1 px-5 py-7"><p className={`mb-5 text-xs font-semibold ${featured?"text-slate-300":"text-slate-500 dark:text-slate-400"}`}>{tr(plan.description)}</p><ul className="space-y-5">{plan.features.map(feature=><li key={feature} className="flex items-start gap-3 text-sm leading-6"><Check size={17} className={`mt-1 shrink-0 ${featured?"text-blue-400":"text-slate-400"}`}/><span>{tr(feature)}</span></li>)}</ul></div></article>;})}</div><div className="mt-8 text-center"><Link href={destination} className="inline-flex min-h-11 items-center gap-2 text-sm text-slate-600 hover:text-slate-950 dark:text-slate-300 dark:hover:text-white">{tr(paid?"Continue to my first campaign":"Skip for now. Start free")}<ArrowRight size={15}/></Link></div>
 </section>;
}
