import {describe,it,expect} from 'vitest';
import {readFileSync,existsSync} from 'node:fs';
import {DOCS_ARTICLES,DOCS_GROUPS} from './index';
import {DOCS_SCREENSHOTS,articleWithScreenshots} from './screenshots';
describe('public documentation',()=>{
 it('covers every reference article with one canonical AP3K route',()=>{expect(DOCS_ARTICLES).toHaveLength(77);expect(new Set(DOCS_ARTICLES.map(a=>a.slug)).size).toBe(77);for(const a of DOCS_ARTICLES){expect(DOCS_GROUPS.some(g=>g.id===a.group)).toBe(true);expect(a.title.length).toBeGreaterThan(5);expect(a.html.length).toBeGreaterThan(150);expect(a.html).not.toMatch(/<script|javascript:|onerror=|linktodm|\/docs\/_astro/i)}});
 it('resolves internal documentation links and section anchors',()=>{for(const a of DOCS_ARTICLES){for(const match of Array.from(a.html.matchAll(/href="(\/docs\/[^"?]+)"/g))){const [path,fragment]=match[1].split('#');const target=DOCS_ARTICLES.find(d=>`/docs/${d.slug}`===path.replace(/\/$/,''));expect(target,`${a.slug} -> ${path}`).toBeTruthy();if(fragment&&target)expect(target.html,`${path}#${fragment}`).toContain(`id="${fragment}"`)}}});
 it('uses actual local screenshots and accessible enlargement controls',()=>{for(const [slug,shots] of Object.entries(DOCS_SCREENSHOTS)){const a=DOCS_ARTICLES.find(a=>a.slug===slug);expect(a,slug).toBeTruthy();for(const s of shots)expect(existsSync(`public/images/docs/${s.file}.webp`),s.file).toBe(true);expect(articleWithScreenshots(slug,a!.html)).toContain('role="button"')}});
 it('keeps tutorial screenshots in instructional order',()=>{const a=DOCS_ARTICLES.find(a=>a.video)!;const html=articleWithScreenshots(a.slug,a.html);expect(html.indexOf('/images/docs/create.webp')).toBeLessThan(html.indexOf('/images/docs/trigger.webp'));expect(html.indexOf('/images/docs/trigger.webp')).toBeLessThan(html.indexOf('/images/docs/message.webp'))});
 it('embeds the requested tutorial without autoplay',()=>{const source=readFileSync('components/docs/tutorial-video.tsx','utf8');expect(source).toContain('youtube-nocookie.com/embed/SSOYGbfwLUQ');expect(source).not.toContain('autoplay=1');expect(DOCS_ARTICLES.filter(a=>a.video).map(a=>a.slug)).toEqual(['post-automation/create-instagram-comment-to-dm-automation'])});
 it('removes the launch-kit signup block from public rendering',()=>{for(const path of ['app/(website)/blog/[slug]/page.tsx','app/(website)/resources/[slug]/page.tsx'])expect(readFileSync(path,'utf8')).not.toContain('LaunchKitForm');expect(existsSync('components/website/launch-kit-form.tsx')).toBe(false)});
});
