import { AP3K_PRICING } from "../billing-plans";
import { PLAN_LIMITS } from "../plan-limits";
import type { DocsArticle } from "./types";

const templateSections = [
  { id: "choose-a-job", text: "Choose the customer request first", body: `<p>A template is an editable starting point, not a finished campaign. Decide what the person asked for and what should happen next: a resource link, product details, a follow request or a contact-collection question. Choose the smallest template that serves that request.</p><p>Open <strong>New automation → Browse templates</strong>. Use the Basic and Flow filters or search for the job. Read the card’s trigger and paid-plan indicator. A Basic-category card can still open a Flow editor when the workflow needs several steps; category and execution type are not the same thing.</p>` },
  { id: "template-selection", text: "Match the template to the interaction", body: `<table><thead><tr><th>Customer interaction</th><th>Starting template</th><th>What to verify</th></tr></thead><tbody><tr><td>Comments a resource keyword</td><td>Auto-DM from comments</td><td>Selected media, keyword and final link</td></tr><tr><td>Needs a follow request before delivery</td><td>Grow followers from comments / Ask to follow</td><td>Opener, follow check and final message</td></tr><tr><td>Provides email or phone</td><td>Collect email/phone from comments</td><td>Question, valid response and saved contact</td></tr><tr><td>Sends an inbox message</td><td>Respond to all your DMs</td><td>Whether an any-message response is appropriate</td></tr><tr><td>Mentions your account in a story</td><td>Respond to story mentions</td><td>The actual mention event and response</td></tr><tr><td>Requests a guide with a later reminder</td><td>Deliver a guide and follow up</td><td>Collection, destination, condition and messaging eligibility</td></tr></tbody></table><p>The gallery may add or revise templates. Read the current card and the draft it creates instead of relying on a fixed template count. For your first test, a single post and one resource link are easier to diagnose than a broad account-wide campaign.</p>` },
  { id: "customize-the-draft", text: "Replace every placeholder in the draft", body: `<ol><li><strong>Account and media:</strong> confirm the selected Instagram username and the post, Reel, Story or inbox event. An all-posts or next-post scope needs its own deliberate review.</li><li><strong>Trigger:</strong> use the word promised in the caption. Any Comment is a different rule, not a repair for a keyword mismatch.</li><li><strong>Message:</strong> replace example copy and use the real resource or booking URL. Link-button labels support up to 20 characters; a regular DM message supports up to three link buttons.</li><li><strong>Extra steps:</strong> review the opener, follow gate, collection question, delay and follow-up condition. Remove unnecessary steps before launch.</li><li><strong>Plan and usage:</strong> check paid features and remaining monthly capacity. Unlimited active automations does not mean unlimited sending.</li></ol><p>A template opens as a draft. Saving work does not publish it. Do not reuse example discounts, deadlines or business promises unless they are true for your offer.</p>` },
  { id: "example-guide", text: "Example: deliver a requested checklist", body: `<p>This is an illustrative setup, not a customer result. Caption: “Comment GUIDE for the checklist.” Trigger: the configured GUIDE keyword on the selected post. DM: “Here is the checklist you requested.” Button: “Get checklist,” pointing to your actual page.</p><p>Start with that direct path. If you need email collection, explain why you are asking and test that the value appears on the right contact before final delivery. If you add an opener, the person must complete the interaction. A phone preview is useful for wording and sequence but is not an Instagram delivery receipt.</p>` },
  { id: "test-before-promotion", text: "Test before promoting the campaign", body: `<ul><li>Review the advisory policy check and publish deliberately.</li><li>From another Instagram account, create a fresh matching interaction and confirm the enabled public and private responses.</li><li>Try a non-matching interaction for a keyword-only rule.</li><li>Complete every optional step and open the real destination on a phone.</li><li>Inspect sent, skipped or failed activity and the saved contact where relevant.</li></ul><p>Follow-ups require eligible inbound interaction and an open allowed messaging window. A timer or template does not override Instagram rules. Duplicate protections can intentionally prevent repeated test sends.</p><p>If delivery fails, check the selected account, Live state, source, trigger, permissions and usage before replacing the template. <a href="/docs/troubleshoot/fix-comment-automation-not-working">Use the delivery troubleshooting guide</a>.</p>` },
  { id: "template-faq", text: "Template questions", body: `<p><strong>Can I edit a template?</strong> Yes. Review and customize the resulting draft for your business.</p><p><strong>Does using a template publish it?</strong> No. Review the draft and explicitly publish when ready.</p><p><strong>Are all templates free?</strong> No. Cards indicate paid requirements; collection, custom canvas publishing and other paid features require an eligible plan.</p><p><strong>Does a successful preview guarantee delivery?</strong> No. Test the real interaction from a second account and check activity.</p><p><a href="/docs/post-automation/create-instagram-comment-to-dm-automation">Read the complete setup guide</a> or <a href="/pricing">compare current plans</a>.</p>` },
];
export function reviseProductDocs(article: DocsArticle): DocsArticle {
  if (article.slug === "post-automation/post-automation-templates") return {
    ...article, updated: "2026-10-09", video: true,
    description: "Choose an AP3K automation template, replace placeholder content, check plan requirements and test the complete Instagram delivery path.",
    headings: templateSections.map(s => ({ id: s.id, text: s.text, level: 2 })),
    html: `<p>Use AP3K templates to start a specific customer journey, then review the trigger, messages, links and optional steps before publishing. This guide explains how to select and test a template using the current AP3K gallery.</p>` + templateSections.map(s => `<h2 id="${s.id}">${s.text}</h2>${s.body}`).join(""),
  };
  if (article.slug === "getting-started/ap3k-plans-and-pricing") {
    const rows = (["FREE", "PRO", "BUSINESS"] as const).map(plan => {
      const p = PLAN_LIMITS[plan];
      const price = plan === "FREE" ? 0 : plan === "PRO" ? AP3K_PRICING.PRO_MONTHLY : AP3K_PRICING.BUSINESS_MONTHLY;
      return `<tr><td>${p.label}</td><td>$${price}</td><td>${p.staticRepliesPerMonth.toLocaleString("en")}</td><td>${p.aiRepliesPerMonth.toLocaleString("en")}</td><td>${p.connectedInstagramAccounts}</td><td>${p.activeCampaigns}</td></tr>`;
    }).join("");
    return { ...article, updated: "2026-10-09", html: article.html
      .replace(/<tbody>[\s\S]*?<\/tbody>/, `<tbody>${rows}</tbody>`)
      .replace(/up to ten Instagram accounts/g, `up to ${PLAN_LIMITS.BUSINESS.connectedInstagramAccounts} Instagram accounts`)
      .replace('See <a href="/pricing">pricing</a>', `Annual Pro is $${AP3K_PRICING.PRO_ANNUAL}/year and annual Business is $${AP3K_PRICING.BUSINESS_ANNUAL}/year, charged annually. See <a href="/pricing">pricing</a>`) };
  }
  if (article.slug === "how-tos/add-another-instagram-account") return { ...article, updated: "2026-10-09", html: article.html.replace("Business supports ten", `Business supports ${PLAN_LIMITS.BUSINESS.connectedInstagramAccounts}`) };
  return article;
}
