"use client";
import { useState } from "react";
import CommentEditor from "@/components/automations/comment-editor";
import ChoosePlan from "@/components/onboarding/choose-plan";
import type {WizardData} from "@/hooks/use-wizard";
import { DEFAULT_AI_PROTECTION_RULES } from "@/lib/ai-reply-config";
import { DEFAULT_COMMENT_PROMPT } from "@/lib/automation-copy";
const initial:WizardData={post:{postid:"sample",media:"/images/preview/ola_nordman.jpg",caption:"Comment send and get the guide.",mediaType:"IMAGE"},campaignName:"Preview campaign",triggerMode:"SPECIFIC_KEYWORD",keywords:["send","dm me"],matchingMode:"CONTAINS",sendPrivateDm:true,dmMessage:"Thanks {{username}}! Here is your guide.",messageFormat:"LINK",linkButtons:[{label:"Get the guide",url:"https://ap3k.com"}],followGateRequired:false,openingDmText:"Ready for your guide?",openingDmButtonText:"Send it",openingDmEnabled:false,followRequestDmText:"Follow to get the guide",followRequestButtonText:"I followed",publicReply:"Thanks {{username}}! Check your DMs.",publicReply2:"{{username}}, your guide is on its way.",publicReply3:"See your DMs, {{username}}!",publicReplyEnabled:true,aiReplyEnabled:false,aiReplyTone:"FRIENDLY",aiReplyInstructions:DEFAULT_COMMENT_PROMPT,aiProtectionRules:DEFAULT_AI_PROTECTION_RULES,active:false};
export default function EditorReview({frame,screen}:{frame:boolean;screen:"pricing"|"editor"}){
 const [width,setWidth]=useState(390);const [selected,setSelected]=useState(screen);const [data,setData]=useState(initial);const [error,setError]=useState<string|null>(null);
 if(!frame)return <main className="min-h-screen bg-slate-200 p-4 text-slate-950"><div className="mb-4 flex gap-3"><button onClick={()=>setWidth(390)}>Mobile 390px</button><button onClick={()=>setWidth(1280)}>Desktop 1280px</button><button onClick={()=>setSelected("pricing")}>Pricing screen</button><button onClick={()=>setSelected("editor")}>Automation editor</button></div><iframe title="Responsive review" key={selected} src={`/editor-review?frame=1&screen=${selected}`} style={{width,maxWidth:"100%",height:880,border:0,background:"white"}}/></main>;
 if(screen==="pricing")return <div className="min-h-screen bg-white px-5 py-8 text-slate-950 dark:bg-[#0f172a] dark:text-slate-50"><ChoosePlan slug="preview" paid={false}/></div>;
 return <CommentEditor slug="preview" data={data} update={v=>setData(d=>({...d,...v}))} onSave={()=>setError(data.aiReplyEnabled?"AI only available on paid plans.":"Preview only: no automation was published.")} saving={false} error={error} editingActive={false} posts={[]} postsLoading={false} postsFetching={false} refreshPosts={()=>{}} username="ap3k_preview" avatar="/brand/ap3k-social-avatar.png" connected accountLoading={false} accountError={false} retryAccount={()=>{}} followUpsReady paid={false} aiAvailable={false} commentOnly={false}/>;
}
