import type { BlogPost, BlogSection } from "@/lib/blog";
import scheduling from "./scheduling.json";
import replies from "./quick-replies.json";
import responder from "./autoresponder.json";
import ads from "./lead-ads.json";
import qualification from "./qualification.json";
import measurement from "./measurement.json";
import selection from "./tool-selection.json";
import migration from "./migration.json";
import business from "./business-workflows.json";
import operations from "./operations.json";

type Topic = (typeof scheduling)[number];
type Cluster = { id: string; title: string; keywords: string[]; product: string; context: string; checklist: string[]; posts: Topic[] };
export const EXPANSION_CLUSTERS: Cluster[] = [
  { id: "scheduling", title: "Publishing and campaign handoffs", keywords: ["post scheduler instagram", "automate post instagram", "automate instagram posts", "scheduling app for instagram", "scheduling tool for instagram"], product: "/instagram-comment-to-dm", context: "Publishing and responding are separate jobs. Use Instagram's available publishing tools or a suitable scheduler for the post; AP3K handles supported interaction and reply workflows after the content is live. For a post-specific campaign, confirm the actual media is available, select it and test a new eligible comment after activation. This guide does not describe a native AP3K publishing scheduler or promise automatic attachment to a future post.", checklist: ["The publishing owner and reply-campaign owner know their responsibilities.", "The live caption, configured keyword and destination make the same promise.", "A new test comment produces the expected response on the intended account."], posts: scheduling },
  { id: "quick-replies", title: "Quick replies and message writing", keywords: ["quick reply message for instagram", "instagram auto reply"], product: "/instagram-auto-reply", context: "A quick reply is reusable wording; an automated reply also needs a supported trigger and configured action. Draft the wording first, replace every placeholder and verify any business-specific claim. In AP3K, public replies and DMs are separate choices. Use the channel that fits the request, and keep a human route for questions that need current account, order or availability information. The sample copy here is a starting point to adapt, not a statement about your business.", checklist: ["Prices, availability and service promises have an identified source.", "Every placeholder is replaced or deliberately removed.", "The recipient can understand the next step without another explanation."], posts: replies },
  { id: "autoresponder", title: "Autoresponder quality and AI boundaries", keywords: ["instagram autoresponder", "instagram auto responder", "auto responder for ig", "automated instagram messaging"], product: "/instagram-customer-support-automation", context: "AP3K combines configured response workflows with optional AI features. Use saved copy when an exact answer is required, and maintain approved knowledge when using AI. An automated answer should remain within the product facts and business commitments you can verify. Account access, supported triggers and platform messaging restrictions still apply. Test both a normal request and a question the responder should not answer before expanding its scope.", checklist: ["Approved knowledge has no conflicting or obsolete facts.", "Unsupported questions have a useful, truthful fallback.", "A human reviewer checks accuracy separately from tone and delivery."], posts: responder },
  { id: "lead-ads", title: "Lead ads and paid-to-organic coordination", keywords: ["lead ads on instagram", "instagram lead ads", "instagram lead generation ads"], product: "/instagram-lead-generation", context: "Manage advertising, budgets and lead-form destinations in the appropriate Meta tools. AP3K is not an ad-buying platform and this workflow does not imply a native connection that imports form submissions, ad reporting or CRM records. Its role is supported Instagram interaction and reply automation. Keep paid submissions and organic conversations separate unless you have implemented and verified a reliable connection between the systems.", checklist: ["The ad destination and follow-up owner are identified before launch.", "Form submissions are not mislabeled as DM conversations or purchases.", "Any integration or attribution path has been tested rather than assumed."], posts: ads },
  { id: "qualification", title: "Lead qualification and offer fit", keywords: ["instagram leads", "instagram lead generation"], product: "/instagram-lead-generation", context: "Deliver the item promised in the Instagram post before adding unrelated friction. AP3K can respond to an eligible comment with a configured public reply, DM or both, and keep the interaction visible for follow-up. Further qualification can happen through the supported inbox workflow or your own destination form. Do not describe an unimplemented CRM, branching questionnaire or off-site conversion integration as a native feature.", checklist: ["The first response fulfills the original request.", "Qualification questions support a real next decision.", "The team distinguishes a recorded contact from a qualified opportunity."], posts: qualification },
  { id: "measurement", title: "Measurement and attribution", keywords: ["instagram dm automation", "automated dm instagram"], product: "/instagram-dm-automation", context: "Use AP3K activity to inspect the supported interaction and action stages, then use the appropriate destination or sales system for off-site outcomes. Successfully sent public replies and DMs are automated actions; they do not prove that someone read a message, booked an appointment or paid. Keep dates, units and source limitations visible. Examples in this guide illustrate reporting methods and are not AP3K customer results or forecasts.", checklist: ["Every metric names its source, unit and reporting period.", "Tests, incomplete observations and unknown attribution are labeled.", "The next action addresses the stage supported by the evidence."], posts: measurement },
  { id: "tool-selection", title: "Choosing an Instagram automation tool", keywords: ["instagram automation tool", "automation tools for instagram", "automation instagram", "insta automations"], product: "/instagram-automation-tool", context: "Evaluate the workflow you need rather than the broad word automation. AP3K connects professional Instagram accounts and supports configured comment and messaging workflows; it is not a post scheduler or an ad manager. Check the current pricing page for plans and allowances, and test the specific account and action setup before committing a critical workflow. A product comparison should distinguish verified capabilities, limitations and unanswered questions.", checklist: ["Essential requirements have concrete pass conditions.", "Pricing and feature claims are checked against current information.", "The trial includes failure handling and the operator's daily tasks."], posts: selection },
  { id: "migration", title: "ManyChat alternatives and migration", keywords: ["manychat alternative", "many chat alternatives"], product: "/manychat-alternative", context: "AP3K may fit a focused Instagram workflow, but this guide does not claim complete ManyChat feature parity, an automatic flow importer or a native historical-data transfer. Review each required trigger, action and channel independently. Rebuild only supported behavior, keep approved message copy under your control and avoid leaving overlapping responders active during cutover. Current vendor capabilities and plan details should be verified as part of the decision.", checklist: ["Every important old workflow has a tested replacement or documented gap.", "The cutover avoids duplicate responders for the same interaction.", "The team can pause the new campaign and follow a known recovery plan."], posts: migration },
  { id: "business", title: "Business-specific workflows", keywords: ["auto dm instagram", "instagram lead generation", "instagram automation tool"], product: "/instagram-automation-for-local-business", context: "Use a clear caption request, a matching trigger and a destination that fulfills the offer. AP3K can deliver a configured link through a supported DM workflow; the linked booking, checkout, inventory or application system remains responsible for its own records. A sent message is not a confirmed appointment or purchase. Keep business-specific claims current and test the destination in Instagram's in-app browser before promotion.", checklist: ["The resource is relevant to the post and available as described.", "A named person maintains the destination and handles exceptions.", "Final bookings or purchases are verified in their actual system."], posts: business },
  { id: "operations", title: "Reliable daily operations", keywords: ["instagram dm automation", "automated instagram messaging", "instagram auto reply"], product: "/instagram-automation-for-agencies", context: "Operational clarity makes a small automation library easier to maintain than a large collection of unexplained campaigns. Keep account ownership, campaign purpose and destination responsibility visible. In AP3K, review the selected account, trigger scope and enabled actions before activation, then inspect a real supported test. Use authorized access and preserve useful audit context when changing or retiring workflows.", checklist: ["The campaign has a clear purpose and responsible owner.", "Changes include a test and a record of the intended behavior.", "Unresolved incidents and paused workflows have a next action."], posts: operations },
];

export const EXPANSION_POSTS: BlogPost[] = EXPANSION_CLUSTERS.flatMap(cluster => cluster.posts.map((topic, index) => {
  const sections: BlogSection[] = [
    { heading: "The decision to make", paragraphs: [topic.decision] },
    { heading: "A practical workflow", paragraphs: [], steps: topic.steps.map((body, i) => ({ title: `Step ${i + 1}`, body })) },
    { heading: "Worked example", paragraphs: [topic.example] },
    { heading: "What to avoid", paragraphs: [topic.pitfall] },
    { heading: "Where AP3K fits", paragraphs: [cluster.context], links: [{ label: "Explore the relevant AP3K workflow", href: cluster.product }, { label: "Current plans and allowances", href: "/pricing" }] },
    { heading: "How to judge the result", paragraphs: [topic.measure], bullets: cluster.checklist },
    { heading: "Continue with a related guide", paragraphs: ["Use the next guide for a related decision, or browse the topic library to choose a different workflow."], links: [{ label: cluster.posts[(index + 1) % cluster.posts.length].title, href: `/blog/${cluster.posts[(index + 1) % cluster.posts.length].slug}` }, { label: "Browse all growth and operations guides", href: "/resources/instagram-growth-library" }] },
  ];
  const wordCount = [topic.intro, ...sections.flatMap(s => [s.heading, ...s.paragraphs, ...(s.bullets ?? []), ...(s.steps ?? []).flatMap(step => [step.title, step.body])])].join(" ").split(/\s+/).length;
  return {
    slug: topic.slug, title: topic.title, description: (() => { const first = topic.intro.split(/(?<=\.)\s/)[0]; return first.length > 80 ? first : `${first} Follow a practical workflow with an example and review checklist.`; })(), intro: topic.intro,
    contentLocale: "en", publishedAt: "2026-09-24", updatedAt: "2026-09-24", readingTime: `${Math.max(1, Math.ceil(wordCount / 200))} min read`, wordCount,
    category: cluster.title, keywords: Array.from(new Set([...cluster.keywords, "Instagram automation", "Instagram workflow"])), visual: cluster.id === "measurement" ? "analytics" : "workflow",
    visualAlt: "Illustration of an Instagram interaction connected to a configured response workflow", visualCaption: "Illustration, not a campaign performance result. The configured trigger and actions determine the response.",
    related: [cluster.posts[(index + 1) % cluster.posts.length].slug, cluster.posts[(index + 2) % cluster.posts.length].slug], sections,
  };
}));
